// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderReport.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQOrderReport {
  private MQOrderReport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolfking.jeesite.modules.mq.dto.OrderReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    String getQuarter();
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    com.google.protobuf.ByteString
        getQuarterBytes();

    /**
     * <pre>
     *订单ID
     * </pre>
     *
     * <code>int64 orderId = 3;</code>
     */
    long getOrderId();

    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
     */
    boolean hasCustomer();
    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
     */
    MQCustomer.Customer getCustomer();
    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
     */
    MQCustomer.CustomerOrBuilder getCustomerOrBuilder();

    /**
     * <pre>
     *客服ID
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
     */
    boolean hasKefu();
    /**
     * <pre>
     *客服ID
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
     */
    MQOrderReport.Kefu getKefu();
    /**
     * <pre>
     *客服ID
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
     */
    MQOrderReport.KefuOrBuilder getKefuOrBuilder();

    /**
     * <pre>
     *订单类型
     * 20:下单 30：接单 40：派单 50：上门服务 80:完成 90：退单 100:取消
     * </pre>
     *
     * <code>int32 orderType = 6;</code>
     */
    int getOrderType();

    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>int64 provinceId = 7;</code>
     */
    long getProvinceId();

    /**
     * <code>string provinceName = 8;</code>
     */
    String getProvinceName();
    /**
     * <code>string provinceName = 8;</code>
     */
    com.google.protobuf.ByteString
        getProvinceNameBytes();

    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>int64 cityId = 9;</code>
     */
    long getCityId();

    /**
     * <code>string cityName = 10;</code>
     */
    String getCityName();
    /**
     * <code>string cityName = 10;</code>
     */
    com.google.protobuf.ByteString
        getCityNameBytes();

    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>int64 areaId = 11;</code>
     */
    long getAreaId();

    /**
     * <code>string areaName = 12;</code>
     */
    String getAreaName();
    /**
     * <code>string areaName = 12;</code>
     */
    com.google.protobuf.ByteString
        getAreaNameBytes();

    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 qty = 13;</code>
     */
    int getQty();

    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>double amount = 14;</code>
     */
    double getAmount();

    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>int64 triggerBy = 15;</code>
     */
    long getTriggerBy();

    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 16;</code>
     */
    long getTriggerDate();
  }
  /**
   * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.OrderReport}
   */
  public  static final class OrderReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolfking.jeesite.modules.mq.dto.OrderReport)
      OrderReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderReport.newBuilder() to construct.
    private OrderReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderReport() {
      quarter_ = "";
      provinceName_ = "";
      cityName_ = "";
      areaName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              quarter_ = s;
              break;
            }
            case 24: {

              orderId_ = input.readInt64();
              break;
            }
            case 34: {
              MQCustomer.Customer.Builder subBuilder = null;
              if (customer_ != null) {
                subBuilder = customer_.toBuilder();
              }
              customer_ = input.readMessage(MQCustomer.Customer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(customer_);
                customer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              MQOrderReport.Kefu.Builder subBuilder = null;
              if (kefu_ != null) {
                subBuilder = kefu_.toBuilder();
              }
              kefu_ = input.readMessage(MQOrderReport.Kefu.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(kefu_);
                kefu_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              orderType_ = input.readInt32();
              break;
            }
            case 56: {

              provinceId_ = input.readInt64();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              provinceName_ = s;
              break;
            }
            case 72: {

              cityId_ = input.readInt64();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              cityName_ = s;
              break;
            }
            case 88: {

              areaId_ = input.readInt64();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              areaName_ = s;
              break;
            }
            case 104: {

              qty_ = input.readInt32();
              break;
            }
            case 113: {

              amount_ = input.readDouble();
              break;
            }
            case 120: {

              triggerBy_ = input.readInt64();
              break;
            }
            case 128: {

              triggerDate_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MQOrderReport.OrderReport.class, MQOrderReport.OrderReport.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int QUARTER_FIELD_NUMBER = 2;
    private volatile Object quarter_;
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    public String getQuarter() {
      Object ref = quarter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        quarter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQuarterBytes() {
      Object ref = quarter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        quarter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERID_FIELD_NUMBER = 3;
    private long orderId_;
    /**
     * <pre>
     *订单ID
     * </pre>
     *
     * <code>int64 orderId = 3;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int CUSTOMER_FIELD_NUMBER = 4;
    private MQCustomer.Customer customer_;
    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
     */
    public boolean hasCustomer() {
      return customer_ != null;
    }
    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
     */
    public MQCustomer.Customer getCustomer() {
      return customer_ == null ? MQCustomer.Customer.getDefaultInstance() : customer_;
    }
    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
     */
    public MQCustomer.CustomerOrBuilder getCustomerOrBuilder() {
      return getCustomer();
    }

    public static final int KEFU_FIELD_NUMBER = 5;
    private MQOrderReport.Kefu kefu_;
    /**
     * <pre>
     *客服ID
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
     */
    public boolean hasKefu() {
      return kefu_ != null;
    }
    /**
     * <pre>
     *客服ID
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
     */
    public MQOrderReport.Kefu getKefu() {
      return kefu_ == null ? MQOrderReport.Kefu.getDefaultInstance() : kefu_;
    }
    /**
     * <pre>
     *客服ID
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
     */
    public MQOrderReport.KefuOrBuilder getKefuOrBuilder() {
      return getKefu();
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 6;
    private int orderType_;
    /**
     * <pre>
     *订单类型
     * 20:下单 30：接单 40：派单 50：上门服务 80:完成 90：退单 100:取消
     * </pre>
     *
     * <code>int32 orderType = 6;</code>
     */
    public int getOrderType() {
      return orderType_;
    }

    public static final int PROVINCEID_FIELD_NUMBER = 7;
    private long provinceId_;
    /**
     * <pre>
     *省
     * </pre>
     *
     * <code>int64 provinceId = 7;</code>
     */
    public long getProvinceId() {
      return provinceId_;
    }

    public static final int PROVINCENAME_FIELD_NUMBER = 8;
    private volatile Object provinceName_;
    /**
     * <code>string provinceName = 8;</code>
     */
    public String getProvinceName() {
      Object ref = provinceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        provinceName_ = s;
        return s;
      }
    }
    /**
     * <code>string provinceName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceNameBytes() {
      Object ref = provinceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        provinceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITYID_FIELD_NUMBER = 9;
    private long cityId_;
    /**
     * <pre>
     *市
     * </pre>
     *
     * <code>int64 cityId = 9;</code>
     */
    public long getCityId() {
      return cityId_;
    }

    public static final int CITYNAME_FIELD_NUMBER = 10;
    private volatile Object cityName_;
    /**
     * <code>string cityName = 10;</code>
     */
    public String getCityName() {
      Object ref = cityName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cityName_ = s;
        return s;
      }
    }
    /**
     * <code>string cityName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCityNameBytes() {
      Object ref = cityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AREAID_FIELD_NUMBER = 11;
    private long areaId_;
    /**
     * <pre>
     *区
     * </pre>
     *
     * <code>int64 areaId = 11;</code>
     */
    public long getAreaId() {
      return areaId_;
    }

    public static final int AREANAME_FIELD_NUMBER = 12;
    private volatile Object areaName_;
    /**
     * <code>string areaName = 12;</code>
     */
    public String getAreaName() {
      Object ref = areaName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        areaName_ = s;
        return s;
      }
    }
    /**
     * <code>string areaName = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAreaNameBytes() {
      Object ref = areaName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        areaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QTY_FIELD_NUMBER = 13;
    private int qty_;
    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 qty = 13;</code>
     */
    public int getQty() {
      return qty_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 14;
    private double amount_;
    /**
     * <pre>
     *金额
     * </pre>
     *
     * <code>double amount = 14;</code>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int TRIGGERBY_FIELD_NUMBER = 15;
    private long triggerBy_;
    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>int64 triggerBy = 15;</code>
     */
    public long getTriggerBy() {
      return triggerBy_;
    }

    public static final int TRIGGERDATE_FIELD_NUMBER = 16;
    private long triggerDate_;
    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 16;</code>
     */
    public long getTriggerDate() {
      return triggerDate_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getQuarterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, quarter_);
      }
      if (orderId_ != 0L) {
        output.writeInt64(3, orderId_);
      }
      if (customer_ != null) {
        output.writeMessage(4, getCustomer());
      }
      if (kefu_ != null) {
        output.writeMessage(5, getKefu());
      }
      if (orderType_ != 0) {
        output.writeInt32(6, orderType_);
      }
      if (provinceId_ != 0L) {
        output.writeInt64(7, provinceId_);
      }
      if (!getProvinceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, provinceName_);
      }
      if (cityId_ != 0L) {
        output.writeInt64(9, cityId_);
      }
      if (!getCityNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cityName_);
      }
      if (areaId_ != 0L) {
        output.writeInt64(11, areaId_);
      }
      if (!getAreaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, areaName_);
      }
      if (qty_ != 0) {
        output.writeInt32(13, qty_);
      }
      if (amount_ != 0D) {
        output.writeDouble(14, amount_);
      }
      if (triggerBy_ != 0L) {
        output.writeInt64(15, triggerBy_);
      }
      if (triggerDate_ != 0L) {
        output.writeInt64(16, triggerDate_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getQuarterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, quarter_);
      }
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, orderId_);
      }
      if (customer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCustomer());
      }
      if (kefu_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getKefu());
      }
      if (orderType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, orderType_);
      }
      if (provinceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, provinceId_);
      }
      if (!getProvinceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, provinceName_);
      }
      if (cityId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, cityId_);
      }
      if (!getCityNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cityName_);
      }
      if (areaId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, areaId_);
      }
      if (!getAreaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, areaName_);
      }
      if (qty_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, qty_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, amount_);
      }
      if (triggerBy_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, triggerBy_);
      }
      if (triggerDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(16, triggerDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MQOrderReport.OrderReport)) {
        return super.equals(obj);
      }
      MQOrderReport.OrderReport other = (MQOrderReport.OrderReport) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getQuarter()
          .equals(other.getQuarter());
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && (hasCustomer() == other.hasCustomer());
      if (hasCustomer()) {
        result = result && getCustomer()
            .equals(other.getCustomer());
      }
      result = result && (hasKefu() == other.hasKefu());
      if (hasKefu()) {
        result = result && getKefu()
            .equals(other.getKefu());
      }
      result = result && (getOrderType()
          == other.getOrderType());
      result = result && (getProvinceId()
          == other.getProvinceId());
      result = result && getProvinceName()
          .equals(other.getProvinceName());
      result = result && (getCityId()
          == other.getCityId());
      result = result && getCityName()
          .equals(other.getCityName());
      result = result && (getAreaId()
          == other.getAreaId());
      result = result && getAreaName()
          .equals(other.getAreaName());
      result = result && (getQty()
          == other.getQty());
      result = result && (
          Double.doubleToLongBits(getAmount())
          == Double.doubleToLongBits(
              other.getAmount()));
      result = result && (getTriggerBy()
          == other.getTriggerBy());
      result = result && (getTriggerDate()
          == other.getTriggerDate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + QUARTER_FIELD_NUMBER;
      hash = (53 * hash) + getQuarter().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      if (hasCustomer()) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomer().hashCode();
      }
      if (hasKefu()) {
        hash = (37 * hash) + KEFU_FIELD_NUMBER;
        hash = (53 * hash) + getKefu().hashCode();
      }
      hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderType();
      hash = (37 * hash) + PROVINCEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProvinceId());
      hash = (37 * hash) + PROVINCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getProvinceName().hashCode();
      hash = (37 * hash) + CITYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCityId());
      hash = (37 * hash) + CITYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getCityName().hashCode();
      hash = (37 * hash) + AREAID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAreaId());
      hash = (37 * hash) + AREANAME_FIELD_NUMBER;
      hash = (53 * hash) + getAreaName().hashCode();
      hash = (37 * hash) + QTY_FIELD_NUMBER;
      hash = (53 * hash) + getQty();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + TRIGGERBY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTriggerBy());
      hash = (37 * hash) + TRIGGERDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTriggerDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MQOrderReport.OrderReport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderReport.OrderReport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderReport.OrderReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderReport.OrderReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderReport.OrderReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderReport.OrderReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderReport.OrderReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQOrderReport.OrderReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQOrderReport.OrderReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MQOrderReport.OrderReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQOrderReport.OrderReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQOrderReport.OrderReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MQOrderReport.OrderReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.OrderReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolfking.jeesite.modules.mq.dto.OrderReport)
        MQOrderReport.OrderReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MQOrderReport.OrderReport.class, MQOrderReport.OrderReport.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQOrderReport.OrderReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        quarter_ = "";

        orderId_ = 0L;

        if (customerBuilder_ == null) {
          customer_ = null;
        } else {
          customer_ = null;
          customerBuilder_ = null;
        }
        if (kefuBuilder_ == null) {
          kefu_ = null;
        } else {
          kefu_ = null;
          kefuBuilder_ = null;
        }
        orderType_ = 0;

        provinceId_ = 0L;

        provinceName_ = "";

        cityId_ = 0L;

        cityName_ = "";

        areaId_ = 0L;

        areaName_ = "";

        qty_ = 0;

        amount_ = 0D;

        triggerBy_ = 0L;

        triggerDate_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_descriptor;
      }

      @Override
      public MQOrderReport.OrderReport getDefaultInstanceForType() {
        return MQOrderReport.OrderReport.getDefaultInstance();
      }

      @Override
      public MQOrderReport.OrderReport build() {
        MQOrderReport.OrderReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MQOrderReport.OrderReport buildPartial() {
        MQOrderReport.OrderReport result = new MQOrderReport.OrderReport(this);
        result.id_ = id_;
        result.quarter_ = quarter_;
        result.orderId_ = orderId_;
        if (customerBuilder_ == null) {
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        if (kefuBuilder_ == null) {
          result.kefu_ = kefu_;
        } else {
          result.kefu_ = kefuBuilder_.build();
        }
        result.orderType_ = orderType_;
        result.provinceId_ = provinceId_;
        result.provinceName_ = provinceName_;
        result.cityId_ = cityId_;
        result.cityName_ = cityName_;
        result.areaId_ = areaId_;
        result.areaName_ = areaName_;
        result.qty_ = qty_;
        result.amount_ = amount_;
        result.triggerBy_ = triggerBy_;
        result.triggerDate_ = triggerDate_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MQOrderReport.OrderReport) {
          return mergeFrom((MQOrderReport.OrderReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MQOrderReport.OrderReport other) {
        if (other == MQOrderReport.OrderReport.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getQuarter().isEmpty()) {
          quarter_ = other.quarter_;
          onChanged();
        }
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (other.hasCustomer()) {
          mergeCustomer(other.getCustomer());
        }
        if (other.hasKefu()) {
          mergeKefu(other.getKefu());
        }
        if (other.getOrderType() != 0) {
          setOrderType(other.getOrderType());
        }
        if (other.getProvinceId() != 0L) {
          setProvinceId(other.getProvinceId());
        }
        if (!other.getProvinceName().isEmpty()) {
          provinceName_ = other.provinceName_;
          onChanged();
        }
        if (other.getCityId() != 0L) {
          setCityId(other.getCityId());
        }
        if (!other.getCityName().isEmpty()) {
          cityName_ = other.cityName_;
          onChanged();
        }
        if (other.getAreaId() != 0L) {
          setAreaId(other.getAreaId());
        }
        if (!other.getAreaName().isEmpty()) {
          areaName_ = other.areaName_;
          onChanged();
        }
        if (other.getQty() != 0) {
          setQty(other.getQty());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.getTriggerBy() != 0L) {
          setTriggerBy(other.getTriggerBy());
        }
        if (other.getTriggerDate() != 0L) {
          setTriggerDate(other.getTriggerDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MQOrderReport.OrderReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MQOrderReport.OrderReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object quarter_ = "";
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public String getQuarter() {
        Object ref = quarter_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          quarter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQuarterBytes() {
        Object ref = quarter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          quarter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder setQuarter(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        quarter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder clearQuarter() {

        quarter_ = getDefaultInstance().getQuarter();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder setQuarterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        quarter_ = value;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 3;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 3;</code>
       */
      public Builder setOrderId(long value) {

        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 3;</code>
       */
      public Builder clearOrderId() {

        orderId_ = 0L;
        onChanged();
        return this;
      }

      private MQCustomer.Customer customer_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MQCustomer.Customer, MQCustomer.Customer.Builder, MQCustomer.CustomerOrBuilder> customerBuilder_;
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public boolean hasCustomer() {
        return customerBuilder_ != null || customer_ != null;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public MQCustomer.Customer getCustomer() {
        if (customerBuilder_ == null) {
          return customer_ == null ? MQCustomer.Customer.getDefaultInstance() : customer_;
        } else {
          return customerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public Builder setCustomer(MQCustomer.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          customer_ = value;
          onChanged();
        } else {
          customerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public Builder setCustomer(
          MQCustomer.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          customer_ = builderForValue.build();
          onChanged();
        } else {
          customerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public Builder mergeCustomer(MQCustomer.Customer value) {
        if (customerBuilder_ == null) {
          if (customer_ != null) {
            customer_ =
              MQCustomer.Customer.newBuilder(customer_).mergeFrom(value).buildPartial();
          } else {
            customer_ = value;
          }
          onChanged();
        } else {
          customerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = null;
          onChanged();
        } else {
          customer_ = null;
          customerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public MQCustomer.Customer.Builder getCustomerBuilder() {

        onChanged();
        return getCustomerFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      public MQCustomer.CustomerOrBuilder getCustomerOrBuilder() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilder();
        } else {
          return customer_ == null ?
              MQCustomer.Customer.getDefaultInstance() : customer_;
        }
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Customer customer = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MQCustomer.Customer, MQCustomer.Customer.Builder, MQCustomer.CustomerOrBuilder>
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MQCustomer.Customer, MQCustomer.Customer.Builder, MQCustomer.CustomerOrBuilder>(
                  getCustomer(),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }

      private MQOrderReport.Kefu kefu_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Kefu, Kefu.Builder, KefuOrBuilder> kefuBuilder_;
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public boolean hasKefu() {
        return kefuBuilder_ != null || kefu_ != null;
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public MQOrderReport.Kefu getKefu() {
        if (kefuBuilder_ == null) {
          return kefu_ == null ? MQOrderReport.Kefu.getDefaultInstance() : kefu_;
        } else {
          return kefuBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public Builder setKefu(MQOrderReport.Kefu value) {
        if (kefuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kefu_ = value;
          onChanged();
        } else {
          kefuBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public Builder setKefu(
          MQOrderReport.Kefu.Builder builderForValue) {
        if (kefuBuilder_ == null) {
          kefu_ = builderForValue.build();
          onChanged();
        } else {
          kefuBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public Builder mergeKefu(MQOrderReport.Kefu value) {
        if (kefuBuilder_ == null) {
          if (kefu_ != null) {
            kefu_ =
              MQOrderReport.Kefu.newBuilder(kefu_).mergeFrom(value).buildPartial();
          } else {
            kefu_ = value;
          }
          onChanged();
        } else {
          kefuBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public Builder clearKefu() {
        if (kefuBuilder_ == null) {
          kefu_ = null;
          onChanged();
        } else {
          kefu_ = null;
          kefuBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public MQOrderReport.Kefu.Builder getKefuBuilder() {

        onChanged();
        return getKefuFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      public MQOrderReport.KefuOrBuilder getKefuOrBuilder() {
        if (kefuBuilder_ != null) {
          return kefuBuilder_.getMessageOrBuilder();
        } else {
          return kefu_ == null ?
              MQOrderReport.Kefu.getDefaultInstance() : kefu_;
        }
      }
      /**
       * <pre>
       *客服ID
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.Kefu kefu = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Kefu, Kefu.Builder, KefuOrBuilder>
          getKefuFieldBuilder() {
        if (kefuBuilder_ == null) {
          kefuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Kefu, Kefu.Builder, KefuOrBuilder>(
                  getKefu(),
                  getParentForChildren(),
                  isClean());
          kefu_ = null;
        }
        return kefuBuilder_;
      }

      private int orderType_ ;
      /**
       * <pre>
       *订单类型
       * 20:下单 30：接单 40：派单 50：上门服务 80:完成 90：退单 100:取消
       * </pre>
       *
       * <code>int32 orderType = 6;</code>
       */
      public int getOrderType() {
        return orderType_;
      }
      /**
       * <pre>
       *订单类型
       * 20:下单 30：接单 40：派单 50：上门服务 80:完成 90：退单 100:取消
       * </pre>
       *
       * <code>int32 orderType = 6;</code>
       */
      public Builder setOrderType(int value) {

        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单类型
       * 20:下单 30：接单 40：派单 50：上门服务 80:完成 90：退单 100:取消
       * </pre>
       *
       * <code>int32 orderType = 6;</code>
       */
      public Builder clearOrderType() {

        orderType_ = 0;
        onChanged();
        return this;
      }

      private long provinceId_ ;
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>int64 provinceId = 7;</code>
       */
      public long getProvinceId() {
        return provinceId_;
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>int64 provinceId = 7;</code>
       */
      public Builder setProvinceId(long value) {

        provinceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *省
       * </pre>
       *
       * <code>int64 provinceId = 7;</code>
       */
      public Builder clearProvinceId() {

        provinceId_ = 0L;
        onChanged();
        return this;
      }

      private Object provinceName_ = "";
      /**
       * <code>string provinceName = 8;</code>
       */
      public String getProvinceName() {
        Object ref = provinceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          provinceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string provinceName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceNameBytes() {
        Object ref = provinceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          provinceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string provinceName = 8;</code>
       */
      public Builder setProvinceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        provinceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string provinceName = 8;</code>
       */
      public Builder clearProvinceName() {

        provinceName_ = getDefaultInstance().getProvinceName();
        onChanged();
        return this;
      }
      /**
       * <code>string provinceName = 8;</code>
       */
      public Builder setProvinceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        provinceName_ = value;
        onChanged();
        return this;
      }

      private long cityId_ ;
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>int64 cityId = 9;</code>
       */
      public long getCityId() {
        return cityId_;
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>int64 cityId = 9;</code>
       */
      public Builder setCityId(long value) {

        cityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *市
       * </pre>
       *
       * <code>int64 cityId = 9;</code>
       */
      public Builder clearCityId() {

        cityId_ = 0L;
        onChanged();
        return this;
      }

      private Object cityName_ = "";
      /**
       * <code>string cityName = 10;</code>
       */
      public String getCityName() {
        Object ref = cityName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cityName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cityName = 10;</code>
       */
      public com.google.protobuf.ByteString
          getCityNameBytes() {
        Object ref = cityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cityName = 10;</code>
       */
      public Builder setCityName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        cityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cityName = 10;</code>
       */
      public Builder clearCityName() {

        cityName_ = getDefaultInstance().getCityName();
        onChanged();
        return this;
      }
      /**
       * <code>string cityName = 10;</code>
       */
      public Builder setCityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        cityName_ = value;
        onChanged();
        return this;
      }

      private long areaId_ ;
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>int64 areaId = 11;</code>
       */
      public long getAreaId() {
        return areaId_;
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>int64 areaId = 11;</code>
       */
      public Builder setAreaId(long value) {

        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区
       * </pre>
       *
       * <code>int64 areaId = 11;</code>
       */
      public Builder clearAreaId() {

        areaId_ = 0L;
        onChanged();
        return this;
      }

      private Object areaName_ = "";
      /**
       * <code>string areaName = 12;</code>
       */
      public String getAreaName() {
        Object ref = areaName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          areaName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string areaName = 12;</code>
       */
      public com.google.protobuf.ByteString
          getAreaNameBytes() {
        Object ref = areaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          areaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string areaName = 12;</code>
       */
      public Builder setAreaName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        areaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string areaName = 12;</code>
       */
      public Builder clearAreaName() {

        areaName_ = getDefaultInstance().getAreaName();
        onChanged();
        return this;
      }
      /**
       * <code>string areaName = 12;</code>
       */
      public Builder setAreaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        areaName_ = value;
        onChanged();
        return this;
      }

      private int qty_ ;
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>int32 qty = 13;</code>
       */
      public int getQty() {
        return qty_;
      }
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>int32 qty = 13;</code>
       */
      public Builder setQty(int value) {

        qty_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数量
       * </pre>
       *
       * <code>int32 qty = 13;</code>
       */
      public Builder clearQty() {

        qty_ = 0;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>double amount = 14;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>double amount = 14;</code>
       */
      public Builder setAmount(double value) {

        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *金额
       * </pre>
       *
       * <code>double amount = 14;</code>
       */
      public Builder clearAmount() {

        amount_ = 0D;
        onChanged();
        return this;
      }

      private long triggerBy_ ;
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 15;</code>
       */
      public long getTriggerBy() {
        return triggerBy_;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 15;</code>
       */
      public Builder setTriggerBy(long value) {

        triggerBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 15;</code>
       */
      public Builder clearTriggerBy() {

        triggerBy_ = 0L;
        onChanged();
        return this;
      }

      private long triggerDate_ ;
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 16;</code>
       */
      public long getTriggerDate() {
        return triggerDate_;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 16;</code>
       */
      public Builder setTriggerDate(long value) {

        triggerDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 16;</code>
       */
      public Builder clearTriggerDate() {

        triggerDate_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.wolfking.jeesite.modules.mq.dto.OrderReport)
    }

    // @@protoc_insertion_point(class_scope:com.wolfking.jeesite.modules.mq.dto.OrderReport)
    private static final MQOrderReport.OrderReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MQOrderReport.OrderReport();
    }

    public static MQOrderReport.OrderReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderReport>
        PARSER = new com.google.protobuf.AbstractParser<OrderReport>() {
      @Override
      public OrderReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderReport> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderReport> getParserForType() {
      return PARSER;
    }

    @Override
    public MQOrderReport.OrderReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KefuOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolfking.jeesite.modules.mq.dto.Kefu)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   *用户
   * </pre>
   *
   * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.Kefu}
   */
  public  static final class Kefu extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolfking.jeesite.modules.mq.dto.Kefu)
      KefuOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Kefu.newBuilder() to construct.
    private Kefu(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Kefu() {
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Kefu(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MQOrderReport.Kefu.class, MQOrderReport.Kefu.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MQOrderReport.Kefu)) {
        return super.equals(obj);
      }
      MQOrderReport.Kefu other = (MQOrderReport.Kefu) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MQOrderReport.Kefu parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderReport.Kefu parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderReport.Kefu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderReport.Kefu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderReport.Kefu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderReport.Kefu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderReport.Kefu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQOrderReport.Kefu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQOrderReport.Kefu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MQOrderReport.Kefu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQOrderReport.Kefu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQOrderReport.Kefu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MQOrderReport.Kefu prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *用户
     * </pre>
     *
     * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.Kefu}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolfking.jeesite.modules.mq.dto.Kefu)
        MQOrderReport.KefuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MQOrderReport.Kefu.class, MQOrderReport.Kefu.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQOrderReport.Kefu.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MQOrderReport.internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_descriptor;
      }

      @Override
      public MQOrderReport.Kefu getDefaultInstanceForType() {
        return MQOrderReport.Kefu.getDefaultInstance();
      }

      @Override
      public MQOrderReport.Kefu build() {
        MQOrderReport.Kefu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MQOrderReport.Kefu buildPartial() {
        MQOrderReport.Kefu result = new MQOrderReport.Kefu(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MQOrderReport.Kefu) {
          return mergeFrom((MQOrderReport.Kefu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MQOrderReport.Kefu other) {
        if (other == MQOrderReport.Kefu.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MQOrderReport.Kefu parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MQOrderReport.Kefu) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.wolfking.jeesite.modules.mq.dto.Kefu)
    }

    // @@protoc_insertion_point(class_scope:com.wolfking.jeesite.modules.mq.dto.Kefu)
    private static final MQOrderReport.Kefu DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MQOrderReport.Kefu();
    }

    public static MQOrderReport.Kefu getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Kefu>
        PARSER = new com.google.protobuf.AbstractParser<Kefu>() {
      @Override
      public Kefu parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Kefu(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Kefu> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Kefu> getParserForType() {
      return PARSER;
    }

    @Override
    public MQOrderReport.Kefu getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021OrderReport.proto\022#com.wolfking.jeesit" +
      "e.modules.mq.dto\032\016Customer.proto\"\373\002\n\013Ord" +
      "erReport\022\n\n\002id\030\001 \001(\003\022\017\n\007quarter\030\002 \001(\t\022\017\n" +
      "\007orderId\030\003 \001(\003\022?\n\010customer\030\004 \001(\0132-.com.w" +
      "olfking.jeesite.modules.mq.dto.Customer\022" +
      "7\n\004kefu\030\005 \001(\0132).com.wolfking.jeesite.mod" +
      "ules.mq.dto.Kefu\022\021\n\torderType\030\006 \001(\005\022\022\n\np" +
      "rovinceId\030\007 \001(\003\022\024\n\014provinceName\030\010 \001(\t\022\016\n" +
      "\006cityId\030\t \001(\003\022\020\n\010cityName\030\n \001(\t\022\016\n\006areaI" +
      "d\030\013 \001(\003\022\020\n\010areaName\030\014 \001(\t\022\013\n\003qty\030\r \001(\005\022\016" +
      "\n\006amount\030\016 \001(\001\022\021\n\ttriggerBy\030\017 \001(\003\022\023\n\013tri" +
      "ggerDate\030\020 \001(\003\" \n\004Kefu\022\n\n\002id\030\001 \001(\003\022\014\n\004na" +
      "me\030\002 \001(\tB\017B\rMQOrderReportb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MQCustomer.getDescriptor(),
        }, assigner);
    internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolfking_jeesite_modules_mq_dto_OrderReport_descriptor,
        new String[] { "Id", "Quarter", "OrderId", "Customer", "Kefu", "OrderType", "ProvinceId", "ProvinceName", "CityId", "CityName", "AreaId", "AreaName", "Qty", "Amount", "TriggerBy", "TriggerDate", });
    internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolfking_jeesite_modules_mq_dto_Kefu_descriptor,
        new String[] { "Id", "Name", });
    MQCustomer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
