// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderAutoComplete.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQOrderAutoComplete {
  private MQOrderAutoComplete() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderAutoCompleteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderAutoComplete)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *订单ID
     * </pre>
     *
     * <code>int64 orderId = 1;</code>
     */
    long getOrderId();

    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    java.lang.String getQuarter();
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    com.google.protobuf.ByteString
        getQuarterBytes();

    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>int64 triggerBy = 3;</code>
     */
    long getTriggerBy();

    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 4;</code>
     */
    long getTriggerDate();
  }
  /**
   * Protobuf type {@code OrderAutoComplete}
   */
  public  static final class OrderAutoComplete extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderAutoComplete)
      OrderAutoCompleteOrBuilder {
    // Use OrderAutoComplete.newBuilder() to construct.
    private OrderAutoComplete(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderAutoComplete() {
      orderId_ = 0L;
      quarter_ = "";
      triggerBy_ = 0L;
      triggerDate_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private OrderAutoComplete(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              orderId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              quarter_ = s;
              break;
            }
            case 24: {

              triggerBy_ = input.readInt64();
              break;
            }
            case 32: {

              triggerDate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.internal_static_OrderAutoComplete_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.internal_static_OrderAutoComplete_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.class, com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private long orderId_;
    /**
     * <pre>
     *订单ID
     * </pre>
     *
     * <code>int64 orderId = 1;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int QUARTER_FIELD_NUMBER = 2;
    private volatile java.lang.Object quarter_;
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    public java.lang.String getQuarter() {
      java.lang.Object ref = quarter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quarter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    public com.google.protobuf.ByteString
        getQuarterBytes() {
      java.lang.Object ref = quarter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quarter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIGGERBY_FIELD_NUMBER = 3;
    private long triggerBy_;
    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>int64 triggerBy = 3;</code>
     */
    public long getTriggerBy() {
      return triggerBy_;
    }

    public static final int TRIGGERDATE_FIELD_NUMBER = 4;
    private long triggerDate_;
    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 4;</code>
     */
    public long getTriggerDate() {
      return triggerDate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0L) {
        output.writeInt64(1, orderId_);
      }
      if (!getQuarterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, quarter_);
      }
      if (triggerBy_ != 0L) {
        output.writeInt64(3, triggerBy_);
      }
      if (triggerDate_ != 0L) {
        output.writeInt64(4, triggerDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, orderId_);
      }
      if (!getQuarterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, quarter_);
      }
      if (triggerBy_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, triggerBy_);
      }
      if (triggerDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, triggerDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete)) {
        return super.equals(obj);
      }
      com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete other = (com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete) obj;

      boolean result = true;
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && getQuarter()
          .equals(other.getQuarter());
      result = result && (getTriggerBy()
          == other.getTriggerBy());
      result = result && (getTriggerDate()
          == other.getTriggerDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + QUARTER_FIELD_NUMBER;
      hash = (53 * hash) + getQuarter().hashCode();
      hash = (37 * hash) + TRIGGERBY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTriggerBy());
      hash = (37 * hash) + TRIGGERDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTriggerDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderAutoComplete}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderAutoComplete)
        com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoCompleteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.internal_static_OrderAutoComplete_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.internal_static_OrderAutoComplete_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.class, com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderId_ = 0L;

        quarter_ = "";

        triggerBy_ = 0L;

        triggerDate_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.internal_static_OrderAutoComplete_descriptor;
      }

      public com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete getDefaultInstanceForType() {
        return com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.getDefaultInstance();
      }

      public com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete build() {
        com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete buildPartial() {
        com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete result = new com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete(this);
        result.orderId_ = orderId_;
        result.quarter_ = quarter_;
        result.triggerBy_ = triggerBy_;
        result.triggerDate_ = triggerDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete) {
          return mergeFrom((com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete other) {
        if (other == com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete.getDefaultInstance()) return this;
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (!other.getQuarter().isEmpty()) {
          quarter_ = other.quarter_;
          onChanged();
        }
        if (other.getTriggerBy() != 0L) {
          setTriggerBy(other.getTriggerBy());
        }
        if (other.getTriggerDate() != 0L) {
          setTriggerDate(other.getTriggerDate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long orderId_ ;
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 1;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 1;</code>
       */
      public Builder setOrderId(long value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object quarter_ = "";
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public java.lang.String getQuarter() {
        java.lang.Object ref = quarter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          quarter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public com.google.protobuf.ByteString
          getQuarterBytes() {
        java.lang.Object ref = quarter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          quarter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder setQuarter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        quarter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder clearQuarter() {
        
        quarter_ = getDefaultInstance().getQuarter();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder setQuarterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        quarter_ = value;
        onChanged();
        return this;
      }

      private long triggerBy_ ;
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 3;</code>
       */
      public long getTriggerBy() {
        return triggerBy_;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 3;</code>
       */
      public Builder setTriggerBy(long value) {
        
        triggerBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 3;</code>
       */
      public Builder clearTriggerBy() {
        
        triggerBy_ = 0L;
        onChanged();
        return this;
      }

      private long triggerDate_ ;
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 4;</code>
       */
      public long getTriggerDate() {
        return triggerDate_;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 4;</code>
       */
      public Builder setTriggerDate(long value) {
        
        triggerDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 4;</code>
       */
      public Builder clearTriggerDate() {
        
        triggerDate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:OrderAutoComplete)
    }

    // @@protoc_insertion_point(class_scope:OrderAutoComplete)
    private static final com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete();
    }

    public static com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderAutoComplete>
        PARSER = new com.google.protobuf.AbstractParser<OrderAutoComplete>() {
      public OrderAutoComplete parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OrderAutoComplete(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderAutoComplete> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderAutoComplete> getParserForType() {
      return PARSER;
    }

    public com.wolfking.jeesite.modules.mq.dto.MQOrderAutoComplete.OrderAutoComplete getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderAutoComplete_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderAutoComplete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027OrderAutoComplete.proto\"]\n\021OrderAutoCo" +
      "mplete\022\017\n\007orderId\030\001 \001(\003\022\017\n\007quarter\030\002 \001(\t" +
      "\022\021\n\ttriggerBy\030\003 \001(\003\022\023\n\013triggerDate\030\004 \001(\003" +
      "B:\n#com.wolfking.jeesite.modules.mq.dtoB" +
      "\023MQOrderAutoCompleteb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderAutoComplete_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderAutoComplete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderAutoComplete_descriptor,
        new java.lang.String[] { "OrderId", "Quarter", "TriggerBy", "TriggerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
