// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Customer.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQCustomer {
  private MQCustomer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolfking.jeesite.modules.mq.dto.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *客户ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *客户code
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    String getCode();
    /**
     * <pre>
     *客户code
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <pre>
     *客户name
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    String getName();
    /**
     * <pre>
     *客户name
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *签约日期
     * </pre>
     *
     * <code>int64 contractDate = 4;</code>
     */
    long getContractDate();

    /**
     * <pre>
     *业务员ID
     * </pre>
     *
     * <code>int64 salesId = 5;</code>
     */
    long getSalesId();

    /**
     * <pre>
     *业务员
     * </pre>
     *
     * <code>string salesName = 6;</code>
     */
    String getSalesName();
    /**
     * <pre>
     *业务员
     * </pre>
     *
     * <code>string salesName = 6;</code>
     */
    com.google.protobuf.ByteString
        getSalesNameBytes();

    /**
     * <pre>
     *付款方式
     * </pre>
     *
     * <code>int32 paymentType = 7;</code>
     */
    int getPaymentType();

    /**
     * <pre>
     *付款方式名称
     * </pre>
     *
     * <code>string paymentTypeName = 8;</code>
     */
    String getPaymentTypeName();
    /**
     * <pre>
     *付款方式名称
     * </pre>
     *
     * <code>string paymentTypeName = 8;</code>
     */
    com.google.protobuf.ByteString
        getPaymentTypeNameBytes();
  }
  /**
   * <pre>
   *客户
   * </pre>
   *
   * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolfking.jeesite.modules.mq.dto.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      code_ = "";
      name_ = "";
      salesName_ = "";
      paymentTypeName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              contractDate_ = input.readInt64();
              break;
            }
            case 40: {

              salesId_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              salesName_ = s;
              break;
            }
            case 56: {

              paymentType_ = input.readInt32();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              paymentTypeName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MQCustomer.internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MQCustomer.internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MQCustomer.Customer.class, MQCustomer.Customer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *客户ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile Object code_;
    /**
     * <pre>
     *客户code
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    public String getCode() {
      Object ref = code_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户code
     * </pre>
     *
     * <code>string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <pre>
     *客户name
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *客户name
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTRACTDATE_FIELD_NUMBER = 4;
    private long contractDate_;
    /**
     * <pre>
     *签约日期
     * </pre>
     *
     * <code>int64 contractDate = 4;</code>
     */
    public long getContractDate() {
      return contractDate_;
    }

    public static final int SALESID_FIELD_NUMBER = 5;
    private long salesId_;
    /**
     * <pre>
     *业务员ID
     * </pre>
     *
     * <code>int64 salesId = 5;</code>
     */
    public long getSalesId() {
      return salesId_;
    }

    public static final int SALESNAME_FIELD_NUMBER = 6;
    private volatile Object salesName_;
    /**
     * <pre>
     *业务员
     * </pre>
     *
     * <code>string salesName = 6;</code>
     */
    public String getSalesName() {
      Object ref = salesName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        salesName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *业务员
     * </pre>
     *
     * <code>string salesName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSalesNameBytes() {
      Object ref = salesName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        salesName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYMENTTYPE_FIELD_NUMBER = 7;
    private int paymentType_;
    /**
     * <pre>
     *付款方式
     * </pre>
     *
     * <code>int32 paymentType = 7;</code>
     */
    public int getPaymentType() {
      return paymentType_;
    }

    public static final int PAYMENTTYPENAME_FIELD_NUMBER = 8;
    private volatile Object paymentTypeName_;
    /**
     * <pre>
     *付款方式名称
     * </pre>
     *
     * <code>string paymentTypeName = 8;</code>
     */
    public String getPaymentTypeName() {
      Object ref = paymentTypeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        paymentTypeName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *付款方式名称
     * </pre>
     *
     * <code>string paymentTypeName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPaymentTypeNameBytes() {
      Object ref = paymentTypeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paymentTypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (contractDate_ != 0L) {
        output.writeInt64(4, contractDate_);
      }
      if (salesId_ != 0L) {
        output.writeInt64(5, salesId_);
      }
      if (!getSalesNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, salesName_);
      }
      if (paymentType_ != 0) {
        output.writeInt32(7, paymentType_);
      }
      if (!getPaymentTypeNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, paymentTypeName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (contractDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, contractDate_);
      }
      if (salesId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, salesId_);
      }
      if (!getSalesNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, salesName_);
      }
      if (paymentType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, paymentType_);
      }
      if (!getPaymentTypeNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, paymentTypeName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MQCustomer.Customer)) {
        return super.equals(obj);
      }
      MQCustomer.Customer other = (MQCustomer.Customer) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getCode()
          .equals(other.getCode());
      result = result && getName()
          .equals(other.getName());
      result = result && (getContractDate()
          == other.getContractDate());
      result = result && (getSalesId()
          == other.getSalesId());
      result = result && getSalesName()
          .equals(other.getSalesName());
      result = result && (getPaymentType()
          == other.getPaymentType());
      result = result && getPaymentTypeName()
          .equals(other.getPaymentTypeName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CONTRACTDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getContractDate());
      hash = (37 * hash) + SALESID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSalesId());
      hash = (37 * hash) + SALESNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSalesName().hashCode();
      hash = (37 * hash) + PAYMENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentType();
      hash = (37 * hash) + PAYMENTTYPENAME_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentTypeName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MQCustomer.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQCustomer.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQCustomer.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQCustomer.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQCustomer.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQCustomer.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQCustomer.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQCustomer.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQCustomer.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MQCustomer.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQCustomer.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQCustomer.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MQCustomer.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *客户
     * </pre>
     *
     * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolfking.jeesite.modules.mq.dto.Customer)
        MQCustomer.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MQCustomer.internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MQCustomer.internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MQCustomer.Customer.class, MQCustomer.Customer.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQCustomer.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        code_ = "";

        name_ = "";

        contractDate_ = 0L;

        salesId_ = 0L;

        salesName_ = "";

        paymentType_ = 0;

        paymentTypeName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MQCustomer.internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_descriptor;
      }

      @Override
      public MQCustomer.Customer getDefaultInstanceForType() {
        return MQCustomer.Customer.getDefaultInstance();
      }

      @Override
      public MQCustomer.Customer build() {
        MQCustomer.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MQCustomer.Customer buildPartial() {
        MQCustomer.Customer result = new MQCustomer.Customer(this);
        result.id_ = id_;
        result.code_ = code_;
        result.name_ = name_;
        result.contractDate_ = contractDate_;
        result.salesId_ = salesId_;
        result.salesName_ = salesName_;
        result.paymentType_ = paymentType_;
        result.paymentTypeName_ = paymentTypeName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MQCustomer.Customer) {
          return mergeFrom((MQCustomer.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MQCustomer.Customer other) {
        if (other == MQCustomer.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getContractDate() != 0L) {
          setContractDate(other.getContractDate());
        }
        if (other.getSalesId() != 0L) {
          setSalesId(other.getSalesId());
        }
        if (!other.getSalesName().isEmpty()) {
          salesName_ = other.salesName_;
          onChanged();
        }
        if (other.getPaymentType() != 0) {
          setPaymentType(other.getPaymentType());
        }
        if (!other.getPaymentTypeName().isEmpty()) {
          paymentTypeName_ = other.paymentTypeName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MQCustomer.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MQCustomer.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *客户ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *客户ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object code_ = "";
      /**
       * <pre>
       *客户code
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public String getCode() {
        Object ref = code_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *客户code
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户code
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public Builder setCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户code
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public Builder clearCode() {

        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户code
       * </pre>
       *
       * <code>string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        code_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       *客户name
       * </pre>
       *
       * <code>string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *客户name
       * </pre>
       *
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *客户name
       * </pre>
       *
       * <code>string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户name
       * </pre>
       *
       * <code>string name = 3;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户name
       * </pre>
       *
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private long contractDate_ ;
      /**
       * <pre>
       *签约日期
       * </pre>
       *
       * <code>int64 contractDate = 4;</code>
       */
      public long getContractDate() {
        return contractDate_;
      }
      /**
       * <pre>
       *签约日期
       * </pre>
       *
       * <code>int64 contractDate = 4;</code>
       */
      public Builder setContractDate(long value) {

        contractDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *签约日期
       * </pre>
       *
       * <code>int64 contractDate = 4;</code>
       */
      public Builder clearContractDate() {

        contractDate_ = 0L;
        onChanged();
        return this;
      }

      private long salesId_ ;
      /**
       * <pre>
       *业务员ID
       * </pre>
       *
       * <code>int64 salesId = 5;</code>
       */
      public long getSalesId() {
        return salesId_;
      }
      /**
       * <pre>
       *业务员ID
       * </pre>
       *
       * <code>int64 salesId = 5;</code>
       */
      public Builder setSalesId(long value) {

        salesId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务员ID
       * </pre>
       *
       * <code>int64 salesId = 5;</code>
       */
      public Builder clearSalesId() {

        salesId_ = 0L;
        onChanged();
        return this;
      }

      private Object salesName_ = "";
      /**
       * <pre>
       *业务员
       * </pre>
       *
       * <code>string salesName = 6;</code>
       */
      public String getSalesName() {
        Object ref = salesName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          salesName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *业务员
       * </pre>
       *
       * <code>string salesName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSalesNameBytes() {
        Object ref = salesName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          salesName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *业务员
       * </pre>
       *
       * <code>string salesName = 6;</code>
       */
      public Builder setSalesName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        salesName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务员
       * </pre>
       *
       * <code>string salesName = 6;</code>
       */
      public Builder clearSalesName() {

        salesName_ = getDefaultInstance().getSalesName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务员
       * </pre>
       *
       * <code>string salesName = 6;</code>
       */
      public Builder setSalesNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        salesName_ = value;
        onChanged();
        return this;
      }

      private int paymentType_ ;
      /**
       * <pre>
       *付款方式
       * </pre>
       *
       * <code>int32 paymentType = 7;</code>
       */
      public int getPaymentType() {
        return paymentType_;
      }
      /**
       * <pre>
       *付款方式
       * </pre>
       *
       * <code>int32 paymentType = 7;</code>
       */
      public Builder setPaymentType(int value) {

        paymentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *付款方式
       * </pre>
       *
       * <code>int32 paymentType = 7;</code>
       */
      public Builder clearPaymentType() {

        paymentType_ = 0;
        onChanged();
        return this;
      }

      private Object paymentTypeName_ = "";
      /**
       * <pre>
       *付款方式名称
       * </pre>
       *
       * <code>string paymentTypeName = 8;</code>
       */
      public String getPaymentTypeName() {
        Object ref = paymentTypeName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          paymentTypeName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *付款方式名称
       * </pre>
       *
       * <code>string paymentTypeName = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPaymentTypeNameBytes() {
        Object ref = paymentTypeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          paymentTypeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *付款方式名称
       * </pre>
       *
       * <code>string paymentTypeName = 8;</code>
       */
      public Builder setPaymentTypeName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        paymentTypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *付款方式名称
       * </pre>
       *
       * <code>string paymentTypeName = 8;</code>
       */
      public Builder clearPaymentTypeName() {

        paymentTypeName_ = getDefaultInstance().getPaymentTypeName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *付款方式名称
       * </pre>
       *
       * <code>string paymentTypeName = 8;</code>
       */
      public Builder setPaymentTypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        paymentTypeName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.wolfking.jeesite.modules.mq.dto.Customer)
    }

    // @@protoc_insertion_point(class_scope:com.wolfking.jeesite.modules.mq.dto.Customer)
    private static final MQCustomer.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MQCustomer.Customer();
    }

    public static MQCustomer.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @Override
    public MQCustomer.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Customer.proto\022#com.wolfking.jeesite.m" +
      "odules.mq.dto\"\232\001\n\010Customer\022\n\n\002id\030\001 \001(\003\022\014" +
      "\n\004code\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\024\n\014contractDa" +
      "te\030\004 \001(\003\022\017\n\007salesId\030\005 \001(\003\022\021\n\tsalesName\030\006" +
      " \001(\t\022\023\n\013paymentType\030\007 \001(\005\022\027\n\017paymentType" +
      "Name\030\010 \001(\tB\014B\nMQCustomerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolfking_jeesite_modules_mq_dto_Customer_descriptor,
        new String[] { "Id", "Code", "Name", "ContractDate", "SalesId", "SalesName", "PaymentType", "PaymentTypeName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
