// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebSocketMessage.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQWebSocketMessage {
  private MQWebSocketMessage() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WebSocketMessageOrBuilder extends
          // @@protoc_insertion_point(interface_extends:WebSocketMessage)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    java.lang.String getQuarter();
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    com.google.protobuf.ByteString
    getQuarterBytes();

    /**
     * <pre>
     *触发者/发送者
     * </pre>
     *
     * <code>.User triggerBy = 3;</code>
     */
    boolean hasTriggerBy();
    /**
     * <pre>
     *触发者/发送者
     * </pre>
     *
     * <code>.User triggerBy = 3;</code>
     */
    com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User getTriggerBy();
    /**
     * <pre>
     *触发者/发送者
     * </pre>
     *
     * <code>.User triggerBy = 3;</code>
     */
    com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder getTriggerByOrBuilder();

    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 4;</code>
     */
    long getTriggerDate();

    /**
     * <pre>
     *接收者,不为空，则点对点
     * </pre>
     *
     * <code>int64 receiver = 5;</code>
     */
    long getReceiver();

    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>string title = 6;</code>
     */
    java.lang.String getTitle();
    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>string title = 6;</code>
     */
    com.google.protobuf.ByteString
    getTitleBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string context = 7;</code>
     */
    java.lang.String getContext();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string context = 7;</code>
     */
    com.google.protobuf.ByteString
    getContextBytes();

    /**
     * <pre>
     *类型
     *1: 问题反馈   点对点，订阅：/user/queue/notifications
     *2: app异常   点对点，订阅：/user/queue/notifications
     *3: 配件单    点对点，订阅：/user/queue/notifications
     *4: 返件      点对点，订阅：/user/queue/notifications
     *9: 客户公告  群发订阅:/topic/customer的客户端
     *10:公告      群发所有订阅:/topic/notice的客户端
     * </pre>
     *
     * <code>int32 noticeType = 8;</code>
     */
    int getNoticeType();

    /**
     * <pre>
     *订单id
     * </pre>
     *
     * <code>int64 orderId = 9;</code>
     */
    long getOrderId();

    /**
     * <pre>
     *订单号
     * </pre>
     *
     * <code>string orderNo = 10;</code>
     */
    java.lang.String getOrderNo();
    /**
     * <pre>
     *订单号
     * </pre>
     *
     * <code>string orderNo = 10;</code>
     */
    com.google.protobuf.ByteString
    getOrderNoBytes();

    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>int64 customerId = 11;</code>
     */
    long getCustomerId();

    /**
     * <pre>
     *区域
     * </pre>
     *
     * <code>int64 areaId = 12;</code>
     */
    long getAreaId();

    /**
     * <pre>
     *客服
     * </pre>
     *
     * <code>int64 kefuId = 13;</code>
     */
    long getKefuId();

    /**
     * <pre>
     *业务
     * </pre>
     *
     * <code>int64 salesId = 14;</code>
     */
    long getSalesId();

    /**
     * <pre>
     *订单创建者
     * </pre>
     *
     * <code>int64 createId = 15;</code>
     */
    long getCreateId();
  }
  /**
   * Protobuf type {@code WebSocketMessage}
   */
  public  static final class WebSocketMessage extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:WebSocketMessage)
          WebSocketMessageOrBuilder {
    // Use WebSocketMessage.newBuilder() to construct.
    private WebSocketMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebSocketMessage() {
      id_ = 0L;
      quarter_ = "";
      triggerDate_ = 0L;
      receiver_ = 0L;
      title_ = "";
      context_ = "";
      noticeType_ = 0;
      orderId_ = 0L;
      orderNo_ = "";
      customerId_ = 0L;
      areaId_ = 0L;
      kefuId_ = 0L;
      salesId_ = 0L;
      createId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WebSocketMessage(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              quarter_ = s;
              break;
            }
            case 26: {
              com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder subBuilder = null;
              if (triggerBy_ != null) {
                subBuilder = triggerBy_.toBuilder();
              }
              triggerBy_ = input.readMessage(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(triggerBy_);
                triggerBy_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              triggerDate_ = input.readInt64();
              break;
            }
            case 40: {

              receiver_ = input.readInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              context_ = s;
              break;
            }
            case 64: {

              noticeType_ = input.readInt32();
              break;
            }
            case 72: {

              orderId_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              orderNo_ = s;
              break;
            }
            case 88: {

              customerId_ = input.readInt64();
              break;
            }
            case 96: {

              areaId_ = input.readInt64();
              break;
            }
            case 104: {

              kefuId_ = input.readInt64();
              break;
            }
            case 112: {

              salesId_ = input.readInt64();
              break;
            }
            case 120: {

              createId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_WebSocketMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_WebSocketMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.class, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int QUARTER_FIELD_NUMBER = 2;
    private volatile java.lang.Object quarter_;
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    public java.lang.String getQuarter() {
      java.lang.Object ref = quarter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quarter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 2;</code>
     */
    public com.google.protobuf.ByteString
    getQuarterBytes() {
      java.lang.Object ref = quarter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        quarter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIGGERBY_FIELD_NUMBER = 3;
    private com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User triggerBy_;
    /**
     * <pre>
     *触发者/发送者
     * </pre>
     *
     * <code>.User triggerBy = 3;</code>
     */
    public boolean hasTriggerBy() {
      return triggerBy_ != null;
    }
    /**
     * <pre>
     *触发者/发送者
     * </pre>
     *
     * <code>.User triggerBy = 3;</code>
     */
    public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User getTriggerBy() {
      return triggerBy_ == null ? com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.getDefaultInstance() : triggerBy_;
    }
    /**
     * <pre>
     *触发者/发送者
     * </pre>
     *
     * <code>.User triggerBy = 3;</code>
     */
    public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder getTriggerByOrBuilder() {
      return getTriggerBy();
    }

    public static final int TRIGGERDATE_FIELD_NUMBER = 4;
    private long triggerDate_;
    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 4;</code>
     */
    public long getTriggerDate() {
      return triggerDate_;
    }

    public static final int RECEIVER_FIELD_NUMBER = 5;
    private long receiver_;
    /**
     * <pre>
     *接收者,不为空，则点对点
     * </pre>
     *
     * <code>int64 receiver = 5;</code>
     */
    public long getReceiver() {
      return receiver_;
    }

    public static final int TITLE_FIELD_NUMBER = 6;
    private volatile java.lang.Object title_;
    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>string title = 6;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>string title = 6;</code>
     */
    public com.google.protobuf.ByteString
    getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEXT_FIELD_NUMBER = 7;
    private volatile java.lang.Object context_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string context = 7;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        context_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string context = 7;</code>
     */
    public com.google.protobuf.ByteString
    getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTICETYPE_FIELD_NUMBER = 8;
    private int noticeType_;
    /**
     * <pre>
     *类型
     *1: 问题反馈   点对点，订阅：/user/queue/notifications
     *2: app异常   点对点，订阅：/user/queue/notifications
     *3: 配件单    点对点，订阅：/user/queue/notifications
     *4: 返件      点对点，订阅：/user/queue/notifications
     *9: 客户公告  群发订阅:/topic/customer的客户端
     *10:公告      群发所有订阅:/topic/notice的客户端
     * </pre>
     *
     * <code>int32 noticeType = 8;</code>
     */
    public int getNoticeType() {
      return noticeType_;
    }

    public static final int ORDERID_FIELD_NUMBER = 9;
    private long orderId_;
    /**
     * <pre>
     *订单id
     * </pre>
     *
     * <code>int64 orderId = 9;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int ORDERNO_FIELD_NUMBER = 10;
    private volatile java.lang.Object orderNo_;
    /**
     * <pre>
     *订单号
     * </pre>
     *
     * <code>string orderNo = 10;</code>
     */
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderNo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *订单号
     * </pre>
     *
     * <code>string orderNo = 10;</code>
     */
    public com.google.protobuf.ByteString
    getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 11;
    private long customerId_;
    /**
     * <pre>
     *客户
     * </pre>
     *
     * <code>int64 customerId = 11;</code>
     */
    public long getCustomerId() {
      return customerId_;
    }

    public static final int AREAID_FIELD_NUMBER = 12;
    private long areaId_;
    /**
     * <pre>
     *区域
     * </pre>
     *
     * <code>int64 areaId = 12;</code>
     */
    public long getAreaId() {
      return areaId_;
    }

    public static final int KEFUID_FIELD_NUMBER = 13;
    private long kefuId_;
    /**
     * <pre>
     *客服
     * </pre>
     *
     * <code>int64 kefuId = 13;</code>
     */
    public long getKefuId() {
      return kefuId_;
    }

    public static final int SALESID_FIELD_NUMBER = 14;
    private long salesId_;
    /**
     * <pre>
     *业务
     * </pre>
     *
     * <code>int64 salesId = 14;</code>
     */
    public long getSalesId() {
      return salesId_;
    }

    public static final int CREATEID_FIELD_NUMBER = 15;
    private long createId_;
    /**
     * <pre>
     *订单创建者
     * </pre>
     *
     * <code>int64 createId = 15;</code>
     */
    public long getCreateId() {
      return createId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getQuarterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, quarter_);
      }
      if (triggerBy_ != null) {
        output.writeMessage(3, getTriggerBy());
      }
      if (triggerDate_ != 0L) {
        output.writeInt64(4, triggerDate_);
      }
      if (receiver_ != 0L) {
        output.writeInt64(5, receiver_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, title_);
      }
      if (!getContextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, context_);
      }
      if (noticeType_ != 0) {
        output.writeInt32(8, noticeType_);
      }
      if (orderId_ != 0L) {
        output.writeInt64(9, orderId_);
      }
      if (!getOrderNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, orderNo_);
      }
      if (customerId_ != 0L) {
        output.writeInt64(11, customerId_);
      }
      if (areaId_ != 0L) {
        output.writeInt64(12, areaId_);
      }
      if (kefuId_ != 0L) {
        output.writeInt64(13, kefuId_);
      }
      if (salesId_ != 0L) {
        output.writeInt64(14, salesId_);
      }
      if (createId_ != 0L) {
        output.writeInt64(15, createId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(1, id_);
      }
      if (!getQuarterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, quarter_);
      }
      if (triggerBy_ != null) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(3, getTriggerBy());
      }
      if (triggerDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(4, triggerDate_);
      }
      if (receiver_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(5, receiver_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, title_);
      }
      if (!getContextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, context_);
      }
      if (noticeType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(8, noticeType_);
      }
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(9, orderId_);
      }
      if (!getOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, orderNo_);
      }
      if (customerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(11, customerId_);
      }
      if (areaId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(12, areaId_);
      }
      if (kefuId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(13, kefuId_);
      }
      if (salesId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(14, salesId_);
      }
      if (createId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(15, createId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage)) {
        return super.equals(obj);
      }
      com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage other = (com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage) obj;

      boolean result = true;
      result = result && (getId()
              == other.getId());
      result = result && getQuarter()
              .equals(other.getQuarter());
      result = result && (hasTriggerBy() == other.hasTriggerBy());
      if (hasTriggerBy()) {
        result = result && getTriggerBy()
                .equals(other.getTriggerBy());
      }
      result = result && (getTriggerDate()
              == other.getTriggerDate());
      result = result && (getReceiver()
              == other.getReceiver());
      result = result && getTitle()
              .equals(other.getTitle());
      result = result && getContext()
              .equals(other.getContext());
      result = result && (getNoticeType()
              == other.getNoticeType());
      result = result && (getOrderId()
              == other.getOrderId());
      result = result && getOrderNo()
              .equals(other.getOrderNo());
      result = result && (getCustomerId()
              == other.getCustomerId());
      result = result && (getAreaId()
              == other.getAreaId());
      result = result && (getKefuId()
              == other.getKefuId());
      result = result && (getSalesId()
              == other.getSalesId());
      result = result && (getCreateId()
              == other.getCreateId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getId());
      hash = (37 * hash) + QUARTER_FIELD_NUMBER;
      hash = (53 * hash) + getQuarter().hashCode();
      if (hasTriggerBy()) {
        hash = (37 * hash) + TRIGGERBY_FIELD_NUMBER;
        hash = (53 * hash) + getTriggerBy().hashCode();
      }
      hash = (37 * hash) + TRIGGERDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getTriggerDate());
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getReceiver());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
      hash = (37 * hash) + NOTICETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNoticeType();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getOrderId());
      hash = (37 * hash) + ORDERNO_FIELD_NUMBER;
      hash = (53 * hash) + getOrderNo().hashCode();
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getCustomerId());
      hash = (37 * hash) + AREAID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getAreaId());
      hash = (37 * hash) + KEFUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getKefuId());
      hash = (37 * hash) + SALESID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getSalesId());
      hash = (37 * hash) + CREATEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getCreateId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WebSocketMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:WebSocketMessage)
            com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_WebSocketMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_WebSocketMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.class, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        quarter_ = "";

        if (triggerByBuilder_ == null) {
          triggerBy_ = null;
        } else {
          triggerBy_ = null;
          triggerByBuilder_ = null;
        }
        triggerDate_ = 0L;

        receiver_ = 0L;

        title_ = "";

        context_ = "";

        noticeType_ = 0;

        orderId_ = 0L;

        orderNo_ = "";

        customerId_ = 0L;

        areaId_ = 0L;

        kefuId_ = 0L;

        salesId_ = 0L;

        createId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_WebSocketMessage_descriptor;
      }

      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage getDefaultInstanceForType() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.getDefaultInstance();
      }

      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage build() {
        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage buildPartial() {
        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage result = new com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage(this);
        result.id_ = id_;
        result.quarter_ = quarter_;
        if (triggerByBuilder_ == null) {
          result.triggerBy_ = triggerBy_;
        } else {
          result.triggerBy_ = triggerByBuilder_.build();
        }
        result.triggerDate_ = triggerDate_;
        result.receiver_ = receiver_;
        result.title_ = title_;
        result.context_ = context_;
        result.noticeType_ = noticeType_;
        result.orderId_ = orderId_;
        result.orderNo_ = orderNo_;
        result.customerId_ = customerId_;
        result.areaId_ = areaId_;
        result.kefuId_ = kefuId_;
        result.salesId_ = salesId_;
        result.createId_ = createId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage) {
          return mergeFrom((com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage other) {
        if (other == com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getQuarter().isEmpty()) {
          quarter_ = other.quarter_;
          onChanged();
        }
        if (other.hasTriggerBy()) {
          mergeTriggerBy(other.getTriggerBy());
        }
        if (other.getTriggerDate() != 0L) {
          setTriggerDate(other.getTriggerDate());
        }
        if (other.getReceiver() != 0L) {
          setReceiver(other.getReceiver());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getContext().isEmpty()) {
          context_ = other.context_;
          onChanged();
        }
        if (other.getNoticeType() != 0) {
          setNoticeType(other.getNoticeType());
        }
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (!other.getOrderNo().isEmpty()) {
          orderNo_ = other.orderNo_;
          onChanged();
        }
        if (other.getCustomerId() != 0L) {
          setCustomerId(other.getCustomerId());
        }
        if (other.getAreaId() != 0L) {
          setAreaId(other.getAreaId());
        }
        if (other.getKefuId() != 0L) {
          setKefuId(other.getKefuId());
        }
        if (other.getSalesId() != 0L) {
          setSalesId(other.getSalesId());
        }
        if (other.getCreateId() != 0L) {
          setCreateId(other.getCreateId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object quarter_ = "";
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public java.lang.String getQuarter() {
        java.lang.Object ref = quarter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          quarter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public com.google.protobuf.ByteString
      getQuarterBytes() {
        java.lang.Object ref = quarter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          quarter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder setQuarter(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        quarter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder clearQuarter() {

        quarter_ = getDefaultInstance().getQuarter();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 2;</code>
       */
      public Builder setQuarterBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        quarter_ = value;
        onChanged();
        return this;
      }

      private com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User triggerBy_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
              com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder> triggerByBuilder_;
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public boolean hasTriggerBy() {
        return triggerByBuilder_ != null || triggerBy_ != null;
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User getTriggerBy() {
        if (triggerByBuilder_ == null) {
          return triggerBy_ == null ? com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.getDefaultInstance() : triggerBy_;
        } else {
          return triggerByBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public Builder setTriggerBy(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User value) {
        if (triggerByBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          triggerBy_ = value;
          onChanged();
        } else {
          triggerByBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public Builder setTriggerBy(
              com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder builderForValue) {
        if (triggerByBuilder_ == null) {
          triggerBy_ = builderForValue.build();
          onChanged();
        } else {
          triggerByBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public Builder mergeTriggerBy(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User value) {
        if (triggerByBuilder_ == null) {
          if (triggerBy_ != null) {
            triggerBy_ =
                    com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.newBuilder(triggerBy_).mergeFrom(value).buildPartial();
          } else {
            triggerBy_ = value;
          }
          onChanged();
        } else {
          triggerByBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public Builder clearTriggerBy() {
        if (triggerByBuilder_ == null) {
          triggerBy_ = null;
          onChanged();
        } else {
          triggerBy_ = null;
          triggerByBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder getTriggerByBuilder() {

        onChanged();
        return getTriggerByFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder getTriggerByOrBuilder() {
        if (triggerByBuilder_ != null) {
          return triggerByBuilder_.getMessageOrBuilder();
        } else {
          return triggerBy_ == null ?
                  com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.getDefaultInstance() : triggerBy_;
        }
      }
      /**
       * <pre>
       *触发者/发送者
       * </pre>
       *
       * <code>.User triggerBy = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder>
      getTriggerByFieldBuilder() {
        if (triggerByBuilder_ == null) {
          triggerByBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                  com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder>(
                  getTriggerBy(),
                  getParentForChildren(),
                  isClean());
          triggerBy_ = null;
        }
        return triggerByBuilder_;
      }

      private long triggerDate_ ;
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 4;</code>
       */
      public long getTriggerDate() {
        return triggerDate_;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 4;</code>
       */
      public Builder setTriggerDate(long value) {

        triggerDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 4;</code>
       */
      public Builder clearTriggerDate() {

        triggerDate_ = 0L;
        onChanged();
        return this;
      }

      private long receiver_ ;
      /**
       * <pre>
       *接收者,不为空，则点对点
       * </pre>
       *
       * <code>int64 receiver = 5;</code>
       */
      public long getReceiver() {
        return receiver_;
      }
      /**
       * <pre>
       *接收者,不为空，则点对点
       * </pre>
       *
       * <code>int64 receiver = 5;</code>
       */
      public Builder setReceiver(long value) {

        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者,不为空，则点对点
       * </pre>
       *
       * <code>int64 receiver = 5;</code>
       */
      public Builder clearReceiver() {

        receiver_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>string title = 6;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>string title = 6;</code>
       */
      public com.google.protobuf.ByteString
      getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>string title = 6;</code>
       */
      public Builder setTitle(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>string title = 6;</code>
       */
      public Builder clearTitle() {

        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>string title = 6;</code>
       */
      public Builder setTitleBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object context_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string context = 7;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string context = 7;</code>
       */
      public com.google.protobuf.ByteString
      getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string context = 7;</code>
       */
      public Builder setContext(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string context = 7;</code>
       */
      public Builder clearContext() {

        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string context = 7;</code>
       */
      public Builder setContextBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        context_ = value;
        onChanged();
        return this;
      }

      private int noticeType_ ;
      /**
       * <pre>
       *类型
       *1: 问题反馈   点对点，订阅：/user/queue/notifications
       *2: app异常   点对点，订阅：/user/queue/notifications
       *3: 配件单    点对点，订阅：/user/queue/notifications
       *4: 返件      点对点，订阅：/user/queue/notifications
       *9: 客户公告  群发订阅:/topic/customer的客户端
       *10:公告      群发所有订阅:/topic/notice的客户端
       * </pre>
       *
       * <code>int32 noticeType = 8;</code>
       */
      public int getNoticeType() {
        return noticeType_;
      }
      /**
       * <pre>
       *类型
       *1: 问题反馈   点对点，订阅：/user/queue/notifications
       *2: app异常   点对点，订阅：/user/queue/notifications
       *3: 配件单    点对点，订阅：/user/queue/notifications
       *4: 返件      点对点，订阅：/user/queue/notifications
       *9: 客户公告  群发订阅:/topic/customer的客户端
       *10:公告      群发所有订阅:/topic/notice的客户端
       * </pre>
       *
       * <code>int32 noticeType = 8;</code>
       */
      public Builder setNoticeType(int value) {

        noticeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *类型
       *1: 问题反馈   点对点，订阅：/user/queue/notifications
       *2: app异常   点对点，订阅：/user/queue/notifications
       *3: 配件单    点对点，订阅：/user/queue/notifications
       *4: 返件      点对点，订阅：/user/queue/notifications
       *9: 客户公告  群发订阅:/topic/customer的客户端
       *10:公告      群发所有订阅:/topic/notice的客户端
       * </pre>
       *
       * <code>int32 noticeType = 8;</code>
       */
      public Builder clearNoticeType() {

        noticeType_ = 0;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>int64 orderId = 9;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>int64 orderId = 9;</code>
       */
      public Builder setOrderId(long value) {

        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单id
       * </pre>
       *
       * <code>int64 orderId = 9;</code>
       */
      public Builder clearOrderId() {

        orderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderNo_ = "";
      /**
       * <pre>
       *订单号
       * </pre>
       *
       * <code>string orderNo = 10;</code>
       */
      public java.lang.String getOrderNo() {
        java.lang.Object ref = orderNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *订单号
       * </pre>
       *
       * <code>string orderNo = 10;</code>
       */
      public com.google.protobuf.ByteString
      getOrderNoBytes() {
        java.lang.Object ref = orderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          orderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *订单号
       * </pre>
       *
       * <code>string orderNo = 10;</code>
       */
      public Builder setOrderNo(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        orderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单号
       * </pre>
       *
       * <code>string orderNo = 10;</code>
       */
      public Builder clearOrderNo() {

        orderNo_ = getDefaultInstance().getOrderNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单号
       * </pre>
       *
       * <code>string orderNo = 10;</code>
       */
      public Builder setOrderNoBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        orderNo_ = value;
        onChanged();
        return this;
      }

      private long customerId_ ;
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>int64 customerId = 11;</code>
       */
      public long getCustomerId() {
        return customerId_;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>int64 customerId = 11;</code>
       */
      public Builder setCustomerId(long value) {

        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户
       * </pre>
       *
       * <code>int64 customerId = 11;</code>
       */
      public Builder clearCustomerId() {

        customerId_ = 0L;
        onChanged();
        return this;
      }

      private long areaId_ ;
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>int64 areaId = 12;</code>
       */
      public long getAreaId() {
        return areaId_;
      }
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>int64 areaId = 12;</code>
       */
      public Builder setAreaId(long value) {

        areaId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>int64 areaId = 12;</code>
       */
      public Builder clearAreaId() {

        areaId_ = 0L;
        onChanged();
        return this;
      }

      private long kefuId_ ;
      /**
       * <pre>
       *客服
       * </pre>
       *
       * <code>int64 kefuId = 13;</code>
       */
      public long getKefuId() {
        return kefuId_;
      }
      /**
       * <pre>
       *客服
       * </pre>
       *
       * <code>int64 kefuId = 13;</code>
       */
      public Builder setKefuId(long value) {

        kefuId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客服
       * </pre>
       *
       * <code>int64 kefuId = 13;</code>
       */
      public Builder clearKefuId() {

        kefuId_ = 0L;
        onChanged();
        return this;
      }

      private long salesId_ ;
      /**
       * <pre>
       *业务
       * </pre>
       *
       * <code>int64 salesId = 14;</code>
       */
      public long getSalesId() {
        return salesId_;
      }
      /**
       * <pre>
       *业务
       * </pre>
       *
       * <code>int64 salesId = 14;</code>
       */
      public Builder setSalesId(long value) {

        salesId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *业务
       * </pre>
       *
       * <code>int64 salesId = 14;</code>
       */
      public Builder clearSalesId() {

        salesId_ = 0L;
        onChanged();
        return this;
      }

      private long createId_ ;
      /**
       * <pre>
       *订单创建者
       * </pre>
       *
       * <code>int64 createId = 15;</code>
       */
      public long getCreateId() {
        return createId_;
      }
      /**
       * <pre>
       *订单创建者
       * </pre>
       *
       * <code>int64 createId = 15;</code>
       */
      public Builder setCreateId(long value) {

        createId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单创建者
       * </pre>
       *
       * <code>int64 createId = 15;</code>
       */
      public Builder clearCreateId() {

        createId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:WebSocketMessage)
    }

    // @@protoc_insertion_point(class_scope:WebSocketMessage)
    private static final com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage();
    }

    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebSocketMessage>
            PARSER = new com.google.protobuf.AbstractParser<WebSocketMessage>() {
      public WebSocketMessage parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebSocketMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebSocketMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebSocketMessage> getParserForType() {
      return PARSER;
    }

    public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.WebSocketMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
          // @@protoc_insertion_point(interface_extends:User)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <pre>
     *用户类型
     * </pre>
     *
     * <code>int32 userType = 3;</code>
     */
    int getUserType();

    /**
     * <pre>
     *公司id
     * </pre>
     *
     * <code>int64 companyId = 4;</code>
     */
    long getCompanyId();

    /**
     * <pre>
     *部门id
     * </pre>
     *
     * <code>int64 officeId = 5;</code>
     */
    long getOfficeId();
  }
  /**
   * <pre>
   *用户
   * </pre>
   *
   * Protobuf type {@code User}
   */
  public  static final class User extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:User)
          UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0L;
      name_ = "";
      userType_ = 0;
      companyId_ = 0L;
      officeId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private User(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              userType_ = input.readInt32();
              break;
            }
            case 32: {

              companyId_ = input.readInt64();
              break;
            }
            case 40: {

              officeId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_User_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.class, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERTYPE_FIELD_NUMBER = 3;
    private int userType_;
    /**
     * <pre>
     *用户类型
     * </pre>
     *
     * <code>int32 userType = 3;</code>
     */
    public int getUserType() {
      return userType_;
    }

    public static final int COMPANYID_FIELD_NUMBER = 4;
    private long companyId_;
    /**
     * <pre>
     *公司id
     * </pre>
     *
     * <code>int64 companyId = 4;</code>
     */
    public long getCompanyId() {
      return companyId_;
    }

    public static final int OFFICEID_FIELD_NUMBER = 5;
    private long officeId_;
    /**
     * <pre>
     *部门id
     * </pre>
     *
     * <code>int64 officeId = 5;</code>
     */
    public long getOfficeId() {
      return officeId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (userType_ != 0) {
        output.writeInt32(3, userType_);
      }
      if (companyId_ != 0L) {
        output.writeInt64(4, companyId_);
      }
      if (officeId_ != 0L) {
        output.writeInt64(5, officeId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (userType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, userType_);
      }
      if (companyId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(4, companyId_);
      }
      if (officeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(5, officeId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User)) {
        return super.equals(obj);
      }
      com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User other = (com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User) obj;

      boolean result = true;
      result = result && (getId()
              == other.getId());
      result = result && getName()
              .equals(other.getName());
      result = result && (getUserType()
              == other.getUserType());
      result = result && (getCompanyId()
              == other.getCompanyId());
      result = result && (getOfficeId()
              == other.getOfficeId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUserType();
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getCompanyId());
      hash = (37 * hash) + OFFICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getOfficeId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *用户
     * </pre>
     *
     * Protobuf type {@code User}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:User)
            com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_User_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.class, com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        userType_ = 0;

        companyId_ = 0L;

        officeId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.internal_static_User_descriptor;
      }

      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User getDefaultInstanceForType() {
        return com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.getDefaultInstance();
      }

      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User build() {
        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User buildPartial() {
        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User result = new com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User(this);
        result.id_ = id_;
        result.name_ = name_;
        result.userType_ = userType_;
        result.companyId_ = companyId_;
        result.officeId_ = officeId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User) {
          return mergeFrom((com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User other) {
        if (other == com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getUserType() != 0) {
          setUserType(other.getUserType());
        }
        if (other.getCompanyId() != 0L) {
          setCompanyId(other.getCompanyId());
        }
        if (other.getOfficeId() != 0L) {
          setOfficeId(other.getOfficeId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private int userType_ ;
      /**
       * <pre>
       *用户类型
       * </pre>
       *
       * <code>int32 userType = 3;</code>
       */
      public int getUserType() {
        return userType_;
      }
      /**
       * <pre>
       *用户类型
       * </pre>
       *
       * <code>int32 userType = 3;</code>
       */
      public Builder setUserType(int value) {

        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户类型
       * </pre>
       *
       * <code>int32 userType = 3;</code>
       */
      public Builder clearUserType() {

        userType_ = 0;
        onChanged();
        return this;
      }

      private long companyId_ ;
      /**
       * <pre>
       *公司id
       * </pre>
       *
       * <code>int64 companyId = 4;</code>
       */
      public long getCompanyId() {
        return companyId_;
      }
      /**
       * <pre>
       *公司id
       * </pre>
       *
       * <code>int64 companyId = 4;</code>
       */
      public Builder setCompanyId(long value) {

        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *公司id
       * </pre>
       *
       * <code>int64 companyId = 4;</code>
       */
      public Builder clearCompanyId() {

        companyId_ = 0L;
        onChanged();
        return this;
      }

      private long officeId_ ;
      /**
       * <pre>
       *部门id
       * </pre>
       *
       * <code>int64 officeId = 5;</code>
       */
      public long getOfficeId() {
        return officeId_;
      }
      /**
       * <pre>
       *部门id
       * </pre>
       *
       * <code>int64 officeId = 5;</code>
       */
      public Builder setOfficeId(long value) {

        officeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *部门id
       * </pre>
       *
       * <code>int64 officeId = 5;</code>
       */
      public Builder clearOfficeId() {

        officeId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User();
    }

    public static com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
            PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public com.wolfking.jeesite.modules.mq.dto.MQWebSocketMessage.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_WebSocketMessage_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_WebSocketMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_User_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\026WebSocketMessage.proto\"\235\002\n\020WebSocketMe" +
                    "ssage\022\n\n\002id\030\001 \001(\003\022\017\n\007quarter\030\002 \001(\t\022\030\n\ttr" +
                    "iggerBy\030\003 \001(\0132\005.User\022\023\n\013triggerDate\030\004 \001(" +
                    "\003\022\020\n\010receiver\030\005 \001(\003\022\r\n\005title\030\006 \001(\t\022\017\n\007co" +
                    "ntext\030\007 \001(\t\022\022\n\nnoticeType\030\010 \001(\005\022\017\n\007order" +
                    "Id\030\t \001(\003\022\017\n\007orderNo\030\n \001(\t\022\022\n\ncustomerId\030" +
                    "\013 \001(\003\022\016\n\006areaId\030\014 \001(\003\022\016\n\006kefuId\030\r \001(\003\022\017\n" +
                    "\007salesId\030\016 \001(\003\022\020\n\010createId\030\017 \001(\003\"W\n\004User" +
                    "\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010userType\030\003" +
                    " \001(\005\022\021\n\tcompanyId\030\004 \001(\003\022\020\n\010officeId\030\005 \001(",
            "\003B9\n#com.wolfking.jeesite.modules.mq.dto" +
                    "B\022MQWebSocketMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_WebSocketMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_WebSocketMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_WebSocketMessage_descriptor,
            new java.lang.String[] { "Id", "Quarter", "TriggerBy", "TriggerDate", "Receiver", "Title", "Context", "NoticeType", "OrderId", "OrderNo", "CustomerId", "AreaId", "KefuId", "SalesId", "CreateId", });
    internal_static_User_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_User_descriptor,
            new java.lang.String[] { "Id", "Name", "UserType", "CompanyId", "OfficeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
