// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMessage.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQPushMessage {
  private MQPushMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PushMessageType}
   */
  public enum PushMessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *透传
     * </pre>
     *
     * <code>TransparentTransmission = 0;</code>
     */
    TransparentTransmission(0),
    /**
     * <pre>
     *通知
     * </pre>
     *
     * <code>Notification = 1;</code>
     */
    Notification(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *透传
     * </pre>
     *
     * <code>TransparentTransmission = 0;</code>
     */
    public static final int TransparentTransmission_VALUE = 0;
    /**
     * <pre>
     *通知
     * </pre>
     *
     * <code>Notification = 1;</code>
     */
    public static final int Notification_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PushMessageType valueOf(int value) {
      return forNumber(value);
    }

    public static PushMessageType forNumber(int value) {
      switch (value) {
        case 0: return TransparentTransmission;
        case 1: return Notification;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PushMessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PushMessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PushMessageType>() {
            public PushMessageType findValueByNumber(int number) {
              return PushMessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MQPushMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final PushMessageType[] VALUES = values();

    public static PushMessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PushMessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PushMessageType)
  }

  public interface PushMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>optional int64 messageId = 1;</code>
     */
    long getMessageId();

    /**
     * <pre>
     *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
     * </pre>
     *
     * <code>optional .PushMessageType pushMessageType = 2;</code>
     */
    int getPushMessageTypeValue();
    /**
     * <pre>
     *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
     * </pre>
     *
     * <code>optional .PushMessageType pushMessageType = 2;</code>
     */
    PushMessageType getPushMessageType();

    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>optional int64 userId = 3;</code>
     */
    long getUserId();

    /**
     * <pre>
     *消息内容，通知栏中显示的内容
     * </pre>
     *
     * <code>optional string description = 4;</code>
     */
    String getDescription();
    /**
     * <pre>
     *消息内容，通知栏中显示的内容
     * </pre>
     *
     * <code>optional string description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <pre>
     *消息类型：0:系统消息，1:订单消息
     * </pre>
     *
     * <code>optional int32 messageType = 5;</code>
     */
    int getMessageType();

    /**
     * <pre>
     *消息触发时间（13位时间戳）,读卡消息为读卡时间
     * </pre>
     *
     * <code>optional int64 timestamp = 6;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>optional string subject = 7;</code>
     */
    String getSubject();
    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>optional string subject = 7;</code>
     */
    com.google.protobuf.ByteString
        getSubjectBytes();

    /**
     * <pre>
     *消息附加内容
     * </pre>
     *
     * <code>optional string content = 8;</code>
     */
    String getContent();
    /**
     * <pre>
     *消息附加内容
     * </pre>
     *
     * <code>optional string content = 8;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code PushMessage}
   */
  public  static final class PushMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PushMessage)
      PushMessageOrBuilder {
    // Use PushMessage.newBuilder() to construct.
    private PushMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PushMessage() {
      messageId_ = 0L;
      pushMessageType_ = 0;
      userId_ = 0L;
      description_ = "";
      messageType_ = 0;
      timestamp_ = 0L;
      subject_ = "";
      content_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PushMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              messageId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              pushMessageType_ = rawValue;
              break;
            }
            case 24: {

              userId_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 40: {

              messageType_ = input.readInt32();
              break;
            }
            case 48: {

              timestamp_ = input.readInt64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MQPushMessage.internal_static_PushMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MQPushMessage.internal_static_PushMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PushMessage.class, Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>optional int64 messageId = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int PUSHMESSAGETYPE_FIELD_NUMBER = 2;
    private int pushMessageType_;
    /**
     * <pre>
     *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
     * </pre>
     *
     * <code>optional .PushMessageType pushMessageType = 2;</code>
     */
    public int getPushMessageTypeValue() {
      return pushMessageType_;
    }
    /**
     * <pre>
     *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
     * </pre>
     *
     * <code>optional .PushMessageType pushMessageType = 2;</code>
     */
    public PushMessageType getPushMessageType() {
      PushMessageType result = PushMessageType.valueOf(pushMessageType_);
      return result == null ? PushMessageType.UNRECOGNIZED : result;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_;
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>optional int64 userId = 3;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile Object description_;
    /**
     * <pre>
     *消息内容，通知栏中显示的内容
     * </pre>
     *
     * <code>optional string description = 4;</code>
     */
    public String getDescription() {
      Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容，通知栏中显示的内容
     * </pre>
     *
     * <code>optional string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 5;
    private int messageType_;
    /**
     * <pre>
     *消息类型：0:系统消息，1:订单消息
     * </pre>
     *
     * <code>optional int32 messageType = 5;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <pre>
     *消息触发时间（13位时间戳）,读卡消息为读卡时间
     * </pre>
     *
     * <code>optional int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SUBJECT_FIELD_NUMBER = 7;
    private volatile Object subject_;
    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>optional string subject = 7;</code>
     */
    public String getSubject() {
      Object ref = subject_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *主题
     * </pre>
     *
     * <code>optional string subject = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    private volatile Object content_;
    /**
     * <pre>
     *消息附加内容
     * </pre>
     *
     * <code>optional string content = 8;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息附加内容
     * </pre>
     *
     * <code>optional string content = 8;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageId_ != 0L) {
        output.writeInt64(1, messageId_);
      }
      if (pushMessageType_ != PushMessageType.TransparentTransmission.getNumber()) {
        output.writeEnum(2, pushMessageType_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      if (messageType_ != 0) {
        output.writeInt32(5, messageType_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, subject_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, content_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      if (pushMessageType_ != PushMessageType.TransparentTransmission.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, pushMessageType_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, messageType_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, subject_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, content_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PushMessage)) {
        return super.equals(obj);
      }
      PushMessage other = (PushMessage) obj;

      boolean result = true;
      result = result && (getMessageId()
          == other.getMessageId());
      result = result && pushMessageType_ == other.pushMessageType_;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && (getMessageType()
          == other.getMessageType());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getSubject()
          .equals(other.getSubject());
      result = result && getContent()
          .equals(other.getContent());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (37 * hash) + PUSHMESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + pushMessageType_;
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PushMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PushMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PushMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PushMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PushMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PushMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PushMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushMessage)
        PushMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MQPushMessage.internal_static_PushMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MQPushMessage.internal_static_PushMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PushMessage.class, Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQPushMessage.PushMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = 0L;

        pushMessageType_ = 0;

        userId_ = 0L;

        description_ = "";

        messageType_ = 0;

        timestamp_ = 0L;

        subject_ = "";

        content_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MQPushMessage.internal_static_PushMessage_descriptor;
      }

      public PushMessage getDefaultInstanceForType() {
        return PushMessage.getDefaultInstance();
      }

      public PushMessage build() {
        PushMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PushMessage buildPartial() {
        PushMessage result = new PushMessage(this);
        result.messageId_ = messageId_;
        result.pushMessageType_ = pushMessageType_;
        result.userId_ = userId_;
        result.description_ = description_;
        result.messageType_ = messageType_;
        result.timestamp_ = timestamp_;
        result.subject_ = subject_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PushMessage) {
          return mergeFrom((PushMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PushMessage other) {
        if (other == PushMessage.getDefaultInstance()) return this;
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        if (other.pushMessageType_ != 0) {
          setPushMessageTypeValue(other.getPushMessageTypeValue());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PushMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PushMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long messageId_ ;
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional int64 messageId = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional int64 messageId = 1;</code>
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>optional int64 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private int pushMessageType_ = 0;
      /**
       * <pre>
       *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
       * </pre>
       *
       * <code>optional .PushMessageType pushMessageType = 2;</code>
       */
      public int getPushMessageTypeValue() {
        return pushMessageType_;
      }
      /**
       * <pre>
       *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
       * </pre>
       *
       * <code>optional .PushMessageType pushMessageType = 2;</code>
       */
      public Builder setPushMessageTypeValue(int value) {
        pushMessageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
       * </pre>
       *
       * <code>optional .PushMessageType pushMessageType = 2;</code>
       */
      public PushMessageType getPushMessageType() {
        PushMessageType result = PushMessageType.valueOf(pushMessageType_);
        return result == null ? PushMessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
       * </pre>
       *
       * <code>optional .PushMessageType pushMessageType = 2;</code>
       */
      public Builder setPushMessageType(PushMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        pushMessageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型： 1：通知,0:透传消息. 默认为0 注：IOS只有通知.
       * </pre>
       *
       * <code>optional .PushMessageType pushMessageType = 2;</code>
       */
      public Builder clearPushMessageType() {
        
        pushMessageType_ = 0;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>optional int64 userId = 3;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>optional int64 userId = 3;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户ID
       * </pre>
       *
       * <code>optional int64 userId = 3;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private Object description_ = "";
      /**
       * <pre>
       *消息内容，通知栏中显示的内容
       * </pre>
       *
       * <code>optional string description = 4;</code>
       */
      public String getDescription() {
        Object ref = description_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息内容，通知栏中显示的内容
       * </pre>
       *
       * <code>optional string description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容，通知栏中显示的内容
       * </pre>
       *
       * <code>optional string description = 4;</code>
       */
      public Builder setDescription(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容，通知栏中显示的内容
       * </pre>
       *
       * <code>optional string description = 4;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容，通知栏中显示的内容
       * </pre>
       *
       * <code>optional string description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       *消息类型：0:系统消息，1:订单消息
       * </pre>
       *
       * <code>optional int32 messageType = 5;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       *消息类型：0:系统消息，1:订单消息
       * </pre>
       *
       * <code>optional int32 messageType = 5;</code>
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型：0:系统消息，1:订单消息
       * </pre>
       *
       * <code>optional int32 messageType = 5;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *消息触发时间（13位时间戳）,读卡消息为读卡时间
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *消息触发时间（13位时间戳）,读卡消息为读卡时间
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息触发时间（13位时间戳）,读卡消息为读卡时间
       * </pre>
       *
       * <code>optional int64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object subject_ = "";
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>optional string subject = 7;</code>
       */
      public String getSubject() {
        Object ref = subject_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>optional string subject = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSubjectBytes() {
        Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>optional string subject = 7;</code>
       */
      public Builder setSubject(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>optional string subject = 7;</code>
       */
      public Builder clearSubject() {
        
        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主题
       * </pre>
       *
       * <code>optional string subject = 7;</code>
       */
      public Builder setSubjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subject_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       *消息附加内容
       * </pre>
       *
       * <code>optional string content = 8;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息附加内容
       * </pre>
       *
       * <code>optional string content = 8;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息附加内容
       * </pre>
       *
       * <code>optional string content = 8;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息附加内容
       * </pre>
       *
       * <code>optional string content = 8;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息附加内容
       * </pre>
       *
       * <code>optional string content = 8;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PushMessage)
    }

    // @@protoc_insertion_point(class_scope:PushMessage)
    private static final PushMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PushMessage();
    }

    public static PushMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PushMessage>
        PARSER = new com.google.protobuf.AbstractParser<PushMessage>() {
      public PushMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PushMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PushMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PushMessage> getParserForType() {
      return PARSER;
    }

    public PushMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021PushMessage.proto\"\272\001\n\013PushMessage\022\021\n\tm" +
      "essageId\030\001 \001(\003\022)\n\017pushMessageType\030\002 \001(\0162" +
      "\020.PushMessageType\022\016\n\006userId\030\003 \001(\003\022\023\n\013des" +
      "cription\030\004 \001(\t\022\023\n\013messageType\030\005 \001(\005\022\021\n\tt" +
      "imestamp\030\006 \001(\003\022\017\n\007subject\030\007 \001(\t\022\017\n\007conte" +
      "nt\030\010 \001(\t*@\n\017PushMessageType\022\033\n\027Transpare" +
      "ntTransmission\020\000\022\020\n\014Notification\020\001B4\n#co" +
      "m.wolfking.jeesite.modules.mq.dtoB\rMQPus" +
      "hMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PushMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushMessage_descriptor,
        new String[] { "MessageId", "PushMessageType", "UserId", "Description", "MessageType", "Timestamp", "Subject", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
