// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShortMessage.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQShortMessage {
  private MQShortMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShortMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ShortMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 2;</code>
     */
    String getMobile();
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 2;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <pre>
     *区域
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    String getContent();
    /**
     * <pre>
     *区域
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    String getType();
    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 sendTime = 5;</code>
     */
    long getSendTime();

    /**
     * <pre>
     *其他单号
     * </pre>
     *
     * <code>string extNo = 6;</code>
     */
    String getExtNo();
    /**
     * <pre>
     *其他单号
     * </pre>
     *
     * <code>string extNo = 6;</code>
     */
    com.google.protobuf.ByteString
        getExtNoBytes();

    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>int64 triggerBy = 7;</code>
     */
    long getTriggerBy();

    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 8;</code>
     */
    long getTriggerDate();
  }
  /**
   * Protobuf type {@code ShortMessage}
   */
  public  static final class ShortMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ShortMessage)
      ShortMessageOrBuilder {
    // Use ShortMessage.newBuilder() to construct.
    private ShortMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShortMessage() {
      id_ = 0L;
      mobile_ = "";
      content_ = "";
      type_ = "";
      sendTime_ = 0L;
      extNo_ = "";
      triggerBy_ = 0L;
      triggerDate_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ShortMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 40: {

              sendTime_ = input.readInt64();
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              extNo_ = s;
              break;
            }
            case 56: {

              triggerBy_ = input.readInt64();
              break;
            }
            case 64: {

              triggerDate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MQShortMessage.internal_static_ShortMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MQShortMessage.internal_static_ShortMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ShortMessage.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int MOBILE_FIELD_NUMBER = 2;
    private volatile Object mobile_;
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 2;</code>
     */
    public String getMobile() {
      Object ref = mobile_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile Object content_;
    /**
     * <pre>
     *区域
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *区域
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile Object type_;
    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 5;
    private long sendTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>int64 sendTime = 5;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    public static final int EXTNO_FIELD_NUMBER = 6;
    private volatile Object extNo_;
    /**
     * <pre>
     *其他单号
     * </pre>
     *
     * <code>string extNo = 6;</code>
     */
    public String getExtNo() {
      Object ref = extNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extNo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *其他单号
     * </pre>
     *
     * <code>string extNo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExtNoBytes() {
      Object ref = extNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIGGERBY_FIELD_NUMBER = 7;
    private long triggerBy_;
    /**
     * <pre>
     *触发者
     * </pre>
     *
     * <code>int64 triggerBy = 7;</code>
     */
    public long getTriggerBy() {
      return triggerBy_;
    }

    public static final int TRIGGERDATE_FIELD_NUMBER = 8;
    private long triggerDate_;
    /**
     * <pre>
     *触发时间
     * </pre>
     *
     * <code>int64 triggerDate = 8;</code>
     */
    public long getTriggerDate() {
      return triggerDate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mobile_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      if (sendTime_ != 0L) {
        output.writeInt64(5, sendTime_);
      }
      if (!getExtNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, extNo_);
      }
      if (triggerBy_ != 0L) {
        output.writeInt64(7, triggerBy_);
      }
      if (triggerDate_ != 0L) {
        output.writeInt64(8, triggerDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mobile_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sendTime_);
      }
      if (!getExtNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, extNo_);
      }
      if (triggerBy_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, triggerBy_);
      }
      if (triggerDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, triggerDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ShortMessage)) {
        return super.equals(obj);
      }
      ShortMessage other = (ShortMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getMobile()
          .equals(other.getMobile());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getType()
          .equals(other.getType());
      result = result && (getSendTime()
          == other.getSendTime());
      result = result && getExtNo()
          .equals(other.getExtNo());
      result = result && (getTriggerBy()
          == other.getTriggerBy());
      result = result && (getTriggerDate()
          == other.getTriggerDate());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (37 * hash) + EXTNO_FIELD_NUMBER;
      hash = (53 * hash) + getExtNo().hashCode();
      hash = (37 * hash) + TRIGGERBY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTriggerBy());
      hash = (37 * hash) + TRIGGERDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTriggerDate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ShortMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShortMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShortMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShortMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShortMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ShortMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ShortMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ShortMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ShortMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ShortMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ShortMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ShortMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ShortMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ShortMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ShortMessage)
        ShortMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MQShortMessage.internal_static_ShortMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MQShortMessage.internal_static_ShortMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ShortMessage.class, Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQShortMessage.ShortMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        mobile_ = "";

        content_ = "";

        type_ = "";

        sendTime_ = 0L;

        extNo_ = "";

        triggerBy_ = 0L;

        triggerDate_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MQShortMessage.internal_static_ShortMessage_descriptor;
      }

      public ShortMessage getDefaultInstanceForType() {
        return ShortMessage.getDefaultInstance();
      }

      public ShortMessage build() {
        ShortMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ShortMessage buildPartial() {
        ShortMessage result = new ShortMessage(this);
        result.id_ = id_;
        result.mobile_ = mobile_;
        result.content_ = content_;
        result.type_ = type_;
        result.sendTime_ = sendTime_;
        result.extNo_ = extNo_;
        result.triggerBy_ = triggerBy_;
        result.triggerDate_ = triggerDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ShortMessage) {
          return mergeFrom((ShortMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ShortMessage other) {
        if (other == ShortMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        if (!other.getExtNo().isEmpty()) {
          extNo_ = other.extNo_;
          onChanged();
        }
        if (other.getTriggerBy() != 0L) {
          setTriggerBy(other.getTriggerBy());
        }
        if (other.getTriggerDate() != 0L) {
          setTriggerDate(other.getTriggerDate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ShortMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ShortMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object mobile_ = "";
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 2;</code>
       */
      public String getMobile() {
        Object ref = mobile_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 2;</code>
       */
      public Builder setMobile(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 2;</code>
       */
      public Builder clearMobile() {

        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手机号
       * </pre>
       *
       * <code>string mobile = 2;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        mobile_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *区域
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public Builder clearType() {

        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>string type = 4;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        type_ = value;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 sendTime = 5;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 sendTime = 5;</code>
       */
      public Builder setSendTime(long value) {

        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>int64 sendTime = 5;</code>
       */
      public Builder clearSendTime() {

        sendTime_ = 0L;
        onChanged();
        return this;
      }

      private Object extNo_ = "";
      /**
       * <pre>
       *其他单号
       * </pre>
       *
       * <code>string extNo = 6;</code>
       */
      public String getExtNo() {
        Object ref = extNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *其他单号
       * </pre>
       *
       * <code>string extNo = 6;</code>
       */
      public com.google.protobuf.ByteString
          getExtNoBytes() {
        Object ref = extNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *其他单号
       * </pre>
       *
       * <code>string extNo = 6;</code>
       */
      public Builder setExtNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        extNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他单号
       * </pre>
       *
       * <code>string extNo = 6;</code>
       */
      public Builder clearExtNo() {

        extNo_ = getDefaultInstance().getExtNo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他单号
       * </pre>
       *
       * <code>string extNo = 6;</code>
       */
      public Builder setExtNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        extNo_ = value;
        onChanged();
        return this;
      }

      private long triggerBy_ ;
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 7;</code>
       */
      public long getTriggerBy() {
        return triggerBy_;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 7;</code>
       */
      public Builder setTriggerBy(long value) {

        triggerBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发者
       * </pre>
       *
       * <code>int64 triggerBy = 7;</code>
       */
      public Builder clearTriggerBy() {

        triggerBy_ = 0L;
        onChanged();
        return this;
      }

      private long triggerDate_ ;
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 8;</code>
       */
      public long getTriggerDate() {
        return triggerDate_;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 8;</code>
       */
      public Builder setTriggerDate(long value) {

        triggerDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *触发时间
       * </pre>
       *
       * <code>int64 triggerDate = 8;</code>
       */
      public Builder clearTriggerDate() {

        triggerDate_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ShortMessage)
    }

    // @@protoc_insertion_point(class_scope:ShortMessage)
    private static final ShortMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ShortMessage();
    }

    public static ShortMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShortMessage>
        PARSER = new com.google.protobuf.AbstractParser<ShortMessage>() {
      public ShortMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ShortMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShortMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ShortMessage> getParserForType() {
      return PARSER;
    }

    public ShortMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShortMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ShortMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ShortMessage.proto\"\222\001\n\014ShortMessage\022\n\n" +
      "\002id\030\001 \001(\003\022\016\n\006mobile\030\002 \001(\t\022\017\n\007content\030\003 \001" +
      "(\t\022\014\n\004type\030\004 \001(\t\022\020\n\010sendTime\030\005 \001(\003\022\r\n\005ex" +
      "tNo\030\006 \001(\t\022\021\n\ttriggerBy\030\007 \001(\003\022\023\n\013triggerD" +
      "ate\030\010 \001(\003B5\n#com.wolfking.jeesite.module" +
      "s.mq.dtoB\016MQShortMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ShortMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ShortMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ShortMessage_descriptor,
        new String[] { "Id", "Mobile", "Content", "Type", "SendTime", "ExtNo", "TriggerBy", "TriggerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
