// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderProcessLog.proto

package com.wolfking.jeesite.modules.mq.dto;

public final class MQOrderProcessLog {
  private MQOrderProcessLog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderProcessLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.wolfking.jeesite.modules.mq.dto.OrderProcessLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 1;</code>
     */
    String getQuarter();
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 1;</code>
     */
    com.google.protobuf.ByteString
        getQuarterBytes();

    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 2;</code>
     */
    long getId();

    /**
     * <pre>
     *订单ID
     * </pre>
     *
     * <code>int64 orderId = 3;</code>
     */
    long getOrderId();

    /**
     * <pre>
     *处理方式
     * </pre>
     *
     * <code>string action = 4;</code>
     */
    String getAction();
    /**
     * <pre>
     *处理方式
     * </pre>
     *
     * <code>string action = 4;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <pre>
     *处理内容
     * </pre>
     *
     * <code>string actionComment = 5;</code>
     */
    String getActionComment();
    /**
     * <pre>
     *处理内容
     * </pre>
     *
     * <code>string actionComment = 5;</code>
     */
    com.google.protobuf.ByteString
        getActionCommentBytes();

    /**
     * <pre>
     *statusFlag
     * </pre>
     *
     * <code>int32 statusFlag = 6;</code>
     */
    int getStatusFlag();

    /**
     * <pre>
     *订单状态
     * </pre>
     *
     * <code>string status = 7;</code>
     */
    String getStatus();
    /**
     * <pre>
     *订单状态
     * </pre>
     *
     * <code>string status = 7;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <pre>
     *订单状态值
     * </pre>
     *
     * <code>int32 statusValue = 8;</code>
     */
    int getStatusValue();

    /**
     * <pre>
     *关闭标识，1：关闭 2:安维提交的进度跟踪
     * </pre>
     *
     * <code>int32 closeFlag = 9;</code>
     */
    int getCloseFlag();

    /**
     * <pre>
     *createBy
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
     */
    boolean hasCreateBy();
    /**
     * <pre>
     *createBy
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
     */
    MQCommon.User getCreateBy();
    /**
     * <pre>
     *createBy
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
     */
    MQCommon.UserOrBuilder getCreateByOrBuilder();

    /**
     * <pre>
     *createDate
     * </pre>
     *
     * <code>int64 createDate = 11;</code>
     */
    long getCreateDate();

    /**
     * <pre>
     *remarks
     * </pre>
     *
     * <code>string remarks = 12;</code>
     */
    String getRemarks();
    /**
     * <pre>
     *remarks
     * </pre>
     *
     * <code>string remarks = 12;</code>
     */
    com.google.protobuf.ByteString
        getRemarksBytes();
  }
  /**
   * <pre>
   *订单处理日志/跟踪进度
   * </pre>
   *
   * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.OrderProcessLog}
   */
  public  static final class OrderProcessLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.wolfking.jeesite.modules.mq.dto.OrderProcessLog)
      OrderProcessLogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderProcessLog.newBuilder() to construct.
    private OrderProcessLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderProcessLog() {
      quarter_ = "";
      action_ = "";
      actionComment_ = "";
      status_ = "";
      remarks_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderProcessLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              quarter_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 24: {

              orderId_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              actionComment_ = s;
              break;
            }
            case 48: {

              statusFlag_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 64: {

              statusValue_ = input.readInt32();
              break;
            }
            case 72: {

              closeFlag_ = input.readInt32();
              break;
            }
            case 82: {
              MQCommon.User.Builder subBuilder = null;
              if (createBy_ != null) {
                subBuilder = createBy_.toBuilder();
              }
              createBy_ = input.readMessage(MQCommon.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createBy_);
                createBy_ = subBuilder.buildPartial();
              }

              break;
            }
            case 88: {

              createDate_ = input.readInt64();
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              remarks_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MQOrderProcessLog.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MQOrderProcessLog.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MQOrderProcessLog.OrderProcessLog.class, MQOrderProcessLog.OrderProcessLog.Builder.class);
    }

    public static final int QUARTER_FIELD_NUMBER = 1;
    private volatile Object quarter_;
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 1;</code>
     */
    public String getQuarter() {
      Object ref = quarter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        quarter_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *分片
     * </pre>
     *
     * <code>string quarter = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQuarterBytes() {
      Object ref = quarter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        quarter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *ID
     * </pre>
     *
     * <code>int64 id = 2;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int ORDERID_FIELD_NUMBER = 3;
    private long orderId_;
    /**
     * <pre>
     *订单ID
     * </pre>
     *
     * <code>int64 orderId = 3;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int ACTION_FIELD_NUMBER = 4;
    private volatile Object action_;
    /**
     * <pre>
     *处理方式
     * </pre>
     *
     * <code>string action = 4;</code>
     */
    public String getAction() {
      Object ref = action_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *处理方式
     * </pre>
     *
     * <code>string action = 4;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONCOMMENT_FIELD_NUMBER = 5;
    private volatile Object actionComment_;
    /**
     * <pre>
     *处理内容
     * </pre>
     *
     * <code>string actionComment = 5;</code>
     */
    public String getActionComment() {
      Object ref = actionComment_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        actionComment_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *处理内容
     * </pre>
     *
     * <code>string actionComment = 5;</code>
     */
    public com.google.protobuf.ByteString
        getActionCommentBytes() {
      Object ref = actionComment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        actionComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUSFLAG_FIELD_NUMBER = 6;
    private int statusFlag_;
    /**
     * <pre>
     *statusFlag
     * </pre>
     *
     * <code>int32 statusFlag = 6;</code>
     */
    public int getStatusFlag() {
      return statusFlag_;
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private volatile Object status_;
    /**
     * <pre>
     *订单状态
     * </pre>
     *
     * <code>string status = 7;</code>
     */
    public String getStatus() {
      Object ref = status_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *订单状态
     * </pre>
     *
     * <code>string status = 7;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUSVALUE_FIELD_NUMBER = 8;
    private int statusValue_;
    /**
     * <pre>
     *订单状态值
     * </pre>
     *
     * <code>int32 statusValue = 8;</code>
     */
    public int getStatusValue() {
      return statusValue_;
    }

    public static final int CLOSEFLAG_FIELD_NUMBER = 9;
    private int closeFlag_;
    /**
     * <pre>
     *关闭标识，1：关闭 2:安维提交的进度跟踪
     * </pre>
     *
     * <code>int32 closeFlag = 9;</code>
     */
    public int getCloseFlag() {
      return closeFlag_;
    }

    public static final int CREATEBY_FIELD_NUMBER = 10;
    private MQCommon.User createBy_;
    /**
     * <pre>
     *createBy
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
     */
    public boolean hasCreateBy() {
      return createBy_ != null;
    }
    /**
     * <pre>
     *createBy
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
     */
    public MQCommon.User getCreateBy() {
      return createBy_ == null ? MQCommon.User.getDefaultInstance() : createBy_;
    }
    /**
     * <pre>
     *createBy
     * </pre>
     *
     * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
     */
    public MQCommon.UserOrBuilder getCreateByOrBuilder() {
      return getCreateBy();
    }

    public static final int CREATEDATE_FIELD_NUMBER = 11;
    private long createDate_;
    /**
     * <pre>
     *createDate
     * </pre>
     *
     * <code>int64 createDate = 11;</code>
     */
    public long getCreateDate() {
      return createDate_;
    }

    public static final int REMARKS_FIELD_NUMBER = 12;
    private volatile Object remarks_;
    /**
     * <pre>
     *remarks
     * </pre>
     *
     * <code>string remarks = 12;</code>
     */
    public String getRemarks() {
      Object ref = remarks_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        remarks_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *remarks
     * </pre>
     *
     * <code>string remarks = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRemarksBytes() {
      Object ref = remarks_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        remarks_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQuarterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, quarter_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (orderId_ != 0L) {
        output.writeInt64(3, orderId_);
      }
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, action_);
      }
      if (!getActionCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, actionComment_);
      }
      if (statusFlag_ != 0) {
        output.writeInt32(6, statusFlag_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
      }
      if (statusValue_ != 0) {
        output.writeInt32(8, statusValue_);
      }
      if (closeFlag_ != 0) {
        output.writeInt32(9, closeFlag_);
      }
      if (createBy_ != null) {
        output.writeMessage(10, getCreateBy());
      }
      if (createDate_ != 0L) {
        output.writeInt64(11, createDate_);
      }
      if (!getRemarksBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, remarks_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQuarterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, quarter_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, orderId_);
      }
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, action_);
      }
      if (!getActionCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, actionComment_);
      }
      if (statusFlag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, statusFlag_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
      }
      if (statusValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, statusValue_);
      }
      if (closeFlag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, closeFlag_);
      }
      if (createBy_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getCreateBy());
      }
      if (createDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, createDate_);
      }
      if (!getRemarksBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, remarks_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MQOrderProcessLog.OrderProcessLog)) {
        return super.equals(obj);
      }
      MQOrderProcessLog.OrderProcessLog other = (MQOrderProcessLog.OrderProcessLog) obj;

      boolean result = true;
      result = result && getQuarter()
          .equals(other.getQuarter());
      result = result && (getId()
          == other.getId());
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && getAction()
          .equals(other.getAction());
      result = result && getActionComment()
          .equals(other.getActionComment());
      result = result && (getStatusFlag()
          == other.getStatusFlag());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && (getStatusValue()
          == other.getStatusValue());
      result = result && (getCloseFlag()
          == other.getCloseFlag());
      result = result && (hasCreateBy() == other.hasCreateBy());
      if (hasCreateBy()) {
        result = result && getCreateBy()
            .equals(other.getCreateBy());
      }
      result = result && (getCreateDate()
          == other.getCreateDate());
      result = result && getRemarks()
          .equals(other.getRemarks());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUARTER_FIELD_NUMBER;
      hash = (53 * hash) + getQuarter().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + ACTIONCOMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getActionComment().hashCode();
      hash = (37 * hash) + STATUSFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getStatusFlag();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + STATUSVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusValue();
      hash = (37 * hash) + CLOSEFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getCloseFlag();
      if (hasCreateBy()) {
        hash = (37 * hash) + CREATEBY_FIELD_NUMBER;
        hash = (53 * hash) + getCreateBy().hashCode();
      }
      hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateDate());
      hash = (37 * hash) + REMARKS_FIELD_NUMBER;
      hash = (53 * hash) + getRemarks().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQOrderProcessLog.OrderProcessLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MQOrderProcessLog.OrderProcessLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MQOrderProcessLog.OrderProcessLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MQOrderProcessLog.OrderProcessLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *订单处理日志/跟踪进度
     * </pre>
     *
     * Protobuf type {@code com.wolfking.jeesite.modules.mq.dto.OrderProcessLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.wolfking.jeesite.modules.mq.dto.OrderProcessLog)
        MQOrderProcessLog.OrderProcessLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MQOrderProcessLog.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MQOrderProcessLog.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MQOrderProcessLog.OrderProcessLog.class, MQOrderProcessLog.OrderProcessLog.Builder.class);
      }

      // Construct using com.wolfking.jeesite.modules.mq.dto.MQOrderProcessLog.OrderProcessLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        quarter_ = "";

        id_ = 0L;

        orderId_ = 0L;

        action_ = "";

        actionComment_ = "";

        statusFlag_ = 0;

        status_ = "";

        statusValue_ = 0;

        closeFlag_ = 0;

        if (createByBuilder_ == null) {
          createBy_ = null;
        } else {
          createBy_ = null;
          createByBuilder_ = null;
        }
        createDate_ = 0L;

        remarks_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MQOrderProcessLog.internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_descriptor;
      }

      @Override
      public MQOrderProcessLog.OrderProcessLog getDefaultInstanceForType() {
        return MQOrderProcessLog.OrderProcessLog.getDefaultInstance();
      }

      @Override
      public MQOrderProcessLog.OrderProcessLog build() {
        MQOrderProcessLog.OrderProcessLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MQOrderProcessLog.OrderProcessLog buildPartial() {
        MQOrderProcessLog.OrderProcessLog result = new MQOrderProcessLog.OrderProcessLog(this);
        result.quarter_ = quarter_;
        result.id_ = id_;
        result.orderId_ = orderId_;
        result.action_ = action_;
        result.actionComment_ = actionComment_;
        result.statusFlag_ = statusFlag_;
        result.status_ = status_;
        result.statusValue_ = statusValue_;
        result.closeFlag_ = closeFlag_;
        if (createByBuilder_ == null) {
          result.createBy_ = createBy_;
        } else {
          result.createBy_ = createByBuilder_.build();
        }
        result.createDate_ = createDate_;
        result.remarks_ = remarks_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MQOrderProcessLog.OrderProcessLog) {
          return mergeFrom((MQOrderProcessLog.OrderProcessLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MQOrderProcessLog.OrderProcessLog other) {
        if (other == MQOrderProcessLog.OrderProcessLog.getDefaultInstance()) return this;
        if (!other.getQuarter().isEmpty()) {
          quarter_ = other.quarter_;
          onChanged();
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getActionComment().isEmpty()) {
          actionComment_ = other.actionComment_;
          onChanged();
        }
        if (other.getStatusFlag() != 0) {
          setStatusFlag(other.getStatusFlag());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (other.getStatusValue() != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.getCloseFlag() != 0) {
          setCloseFlag(other.getCloseFlag());
        }
        if (other.hasCreateBy()) {
          mergeCreateBy(other.getCreateBy());
        }
        if (other.getCreateDate() != 0L) {
          setCreateDate(other.getCreateDate());
        }
        if (!other.getRemarks().isEmpty()) {
          remarks_ = other.remarks_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MQOrderProcessLog.OrderProcessLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MQOrderProcessLog.OrderProcessLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object quarter_ = "";
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 1;</code>
       */
      public String getQuarter() {
        Object ref = quarter_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          quarter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQuarterBytes() {
        Object ref = quarter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          quarter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 1;</code>
       */
      public Builder setQuarter(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        quarter_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 1;</code>
       */
      public Builder clearQuarter() {

        quarter_ = getDefaultInstance().getQuarter();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *分片
       * </pre>
       *
       * <code>string quarter = 1;</code>
       */
      public Builder setQuarterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        quarter_ = value;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 2;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 2;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ID
       * </pre>
       *
       * <code>int64 id = 2;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 3;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 3;</code>
       */
      public Builder setOrderId(long value) {

        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单ID
       * </pre>
       *
       * <code>int64 orderId = 3;</code>
       */
      public Builder clearOrderId() {

        orderId_ = 0L;
        onChanged();
        return this;
      }

      private Object action_ = "";
      /**
       * <pre>
       *处理方式
       * </pre>
       *
       * <code>string action = 4;</code>
       */
      public String getAction() {
        Object ref = action_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *处理方式
       * </pre>
       *
       * <code>string action = 4;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *处理方式
       * </pre>
       *
       * <code>string action = 4;</code>
       */
      public Builder setAction(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *处理方式
       * </pre>
       *
       * <code>string action = 4;</code>
       */
      public Builder clearAction() {

        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *处理方式
       * </pre>
       *
       * <code>string action = 4;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        action_ = value;
        onChanged();
        return this;
      }

      private Object actionComment_ = "";
      /**
       * <pre>
       *处理内容
       * </pre>
       *
       * <code>string actionComment = 5;</code>
       */
      public String getActionComment() {
        Object ref = actionComment_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          actionComment_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *处理内容
       * </pre>
       *
       * <code>string actionComment = 5;</code>
       */
      public com.google.protobuf.ByteString
          getActionCommentBytes() {
        Object ref = actionComment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          actionComment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *处理内容
       * </pre>
       *
       * <code>string actionComment = 5;</code>
       */
      public Builder setActionComment(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        actionComment_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *处理内容
       * </pre>
       *
       * <code>string actionComment = 5;</code>
       */
      public Builder clearActionComment() {

        actionComment_ = getDefaultInstance().getActionComment();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *处理内容
       * </pre>
       *
       * <code>string actionComment = 5;</code>
       */
      public Builder setActionCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        actionComment_ = value;
        onChanged();
        return this;
      }

      private int statusFlag_ ;
      /**
       * <pre>
       *statusFlag
       * </pre>
       *
       * <code>int32 statusFlag = 6;</code>
       */
      public int getStatusFlag() {
        return statusFlag_;
      }
      /**
       * <pre>
       *statusFlag
       * </pre>
       *
       * <code>int32 statusFlag = 6;</code>
       */
      public Builder setStatusFlag(int value) {

        statusFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *statusFlag
       * </pre>
       *
       * <code>int32 statusFlag = 6;</code>
       */
      public Builder clearStatusFlag() {

        statusFlag_ = 0;
        onChanged();
        return this;
      }

      private Object status_ = "";
      /**
       * <pre>
       *订单状态
       * </pre>
       *
       * <code>string status = 7;</code>
       */
      public String getStatus() {
        Object ref = status_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *订单状态
       * </pre>
       *
       * <code>string status = 7;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *订单状态
       * </pre>
       *
       * <code>string status = 7;</code>
       */
      public Builder setStatus(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单状态
       * </pre>
       *
       * <code>string status = 7;</code>
       */
      public Builder clearStatus() {

        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单状态
       * </pre>
       *
       * <code>string status = 7;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        status_ = value;
        onChanged();
        return this;
      }

      private int statusValue_ ;
      /**
       * <pre>
       *订单状态值
       * </pre>
       *
       * <code>int32 statusValue = 8;</code>
       */
      public int getStatusValue() {
        return statusValue_;
      }
      /**
       * <pre>
       *订单状态值
       * </pre>
       *
       * <code>int32 statusValue = 8;</code>
       */
      public Builder setStatusValue(int value) {

        statusValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *订单状态值
       * </pre>
       *
       * <code>int32 statusValue = 8;</code>
       */
      public Builder clearStatusValue() {

        statusValue_ = 0;
        onChanged();
        return this;
      }

      private int closeFlag_ ;
      /**
       * <pre>
       *关闭标识，1：关闭 2:安维提交的进度跟踪
       * </pre>
       *
       * <code>int32 closeFlag = 9;</code>
       */
      public int getCloseFlag() {
        return closeFlag_;
      }
      /**
       * <pre>
       *关闭标识，1：关闭 2:安维提交的进度跟踪
       * </pre>
       *
       * <code>int32 closeFlag = 9;</code>
       */
      public Builder setCloseFlag(int value) {

        closeFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *关闭标识，1：关闭 2:安维提交的进度跟踪
       * </pre>
       *
       * <code>int32 closeFlag = 9;</code>
       */
      public Builder clearCloseFlag() {

        closeFlag_ = 0;
        onChanged();
        return this;
      }

      private MQCommon.User createBy_;
      private com.google.protobuf.SingleFieldBuilderV3<
          MQCommon.User, MQCommon.User.Builder, MQCommon.UserOrBuilder> createByBuilder_;
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public boolean hasCreateBy() {
        return createByBuilder_ != null || createBy_ != null;
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public MQCommon.User getCreateBy() {
        if (createByBuilder_ == null) {
          return createBy_ == null ? MQCommon.User.getDefaultInstance() : createBy_;
        } else {
          return createByBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public Builder setCreateBy(MQCommon.User value) {
        if (createByBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createBy_ = value;
          onChanged();
        } else {
          createByBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public Builder setCreateBy(
          MQCommon.User.Builder builderForValue) {
        if (createByBuilder_ == null) {
          createBy_ = builderForValue.build();
          onChanged();
        } else {
          createByBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public Builder mergeCreateBy(MQCommon.User value) {
        if (createByBuilder_ == null) {
          if (createBy_ != null) {
            createBy_ =
              MQCommon.User.newBuilder(createBy_).mergeFrom(value).buildPartial();
          } else {
            createBy_ = value;
          }
          onChanged();
        } else {
          createByBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public Builder clearCreateBy() {
        if (createByBuilder_ == null) {
          createBy_ = null;
          onChanged();
        } else {
          createBy_ = null;
          createByBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public MQCommon.User.Builder getCreateByBuilder() {

        onChanged();
        return getCreateByFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      public MQCommon.UserOrBuilder getCreateByOrBuilder() {
        if (createByBuilder_ != null) {
          return createByBuilder_.getMessageOrBuilder();
        } else {
          return createBy_ == null ?
              MQCommon.User.getDefaultInstance() : createBy_;
        }
      }
      /**
       * <pre>
       *createBy
       * </pre>
       *
       * <code>.com.wolfking.jeesite.modules.mq.dto.User createBy = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MQCommon.User, MQCommon.User.Builder, MQCommon.UserOrBuilder>
          getCreateByFieldBuilder() {
        if (createByBuilder_ == null) {
          createByBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MQCommon.User, MQCommon.User.Builder, MQCommon.UserOrBuilder>(
                  getCreateBy(),
                  getParentForChildren(),
                  isClean());
          createBy_ = null;
        }
        return createByBuilder_;
      }

      private long createDate_ ;
      /**
       * <pre>
       *createDate
       * </pre>
       *
       * <code>int64 createDate = 11;</code>
       */
      public long getCreateDate() {
        return createDate_;
      }
      /**
       * <pre>
       *createDate
       * </pre>
       *
       * <code>int64 createDate = 11;</code>
       */
      public Builder setCreateDate(long value) {

        createDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *createDate
       * </pre>
       *
       * <code>int64 createDate = 11;</code>
       */
      public Builder clearCreateDate() {

        createDate_ = 0L;
        onChanged();
        return this;
      }

      private Object remarks_ = "";
      /**
       * <pre>
       *remarks
       * </pre>
       *
       * <code>string remarks = 12;</code>
       */
      public String getRemarks() {
        Object ref = remarks_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          remarks_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *remarks
       * </pre>
       *
       * <code>string remarks = 12;</code>
       */
      public com.google.protobuf.ByteString
          getRemarksBytes() {
        Object ref = remarks_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          remarks_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *remarks
       * </pre>
       *
       * <code>string remarks = 12;</code>
       */
      public Builder setRemarks(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        remarks_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *remarks
       * </pre>
       *
       * <code>string remarks = 12;</code>
       */
      public Builder clearRemarks() {

        remarks_ = getDefaultInstance().getRemarks();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *remarks
       * </pre>
       *
       * <code>string remarks = 12;</code>
       */
      public Builder setRemarksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        remarks_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.wolfking.jeesite.modules.mq.dto.OrderProcessLog)
    }

    // @@protoc_insertion_point(class_scope:com.wolfking.jeesite.modules.mq.dto.OrderProcessLog)
    private static final MQOrderProcessLog.OrderProcessLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MQOrderProcessLog.OrderProcessLog();
    }

    public static MQOrderProcessLog.OrderProcessLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderProcessLog>
        PARSER = new com.google.protobuf.AbstractParser<OrderProcessLog>() {
      @Override
      public OrderProcessLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderProcessLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderProcessLog> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderProcessLog> getParserForType() {
      return PARSER;
    }

    @Override
    public MQOrderProcessLog.OrderProcessLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025OrderProcessLog.proto\022#com.wolfking.je" +
      "esite.modules.mq.dto\032\014Common.proto\"\224\002\n\017O" +
      "rderProcessLog\022\017\n\007quarter\030\001 \001(\t\022\n\n\002id\030\002 " +
      "\001(\003\022\017\n\007orderId\030\003 \001(\003\022\016\n\006action\030\004 \001(\t\022\025\n\r" +
      "actionComment\030\005 \001(\t\022\022\n\nstatusFlag\030\006 \001(\005\022" +
      "\016\n\006status\030\007 \001(\t\022\023\n\013statusValue\030\010 \001(\005\022\021\n\t" +
      "closeFlag\030\t \001(\005\022;\n\010createBy\030\n \001(\0132).com." +
      "wolfking.jeesite.modules.mq.dto.User\022\022\n\n" +
      "createDate\030\013 \001(\003\022\017\n\007remarks\030\014 \001(\tB\023B\021MQO" +
      "rderProcessLogb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          MQCommon.getDescriptor(),
        }, assigner);
    internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wolfking_jeesite_modules_mq_dto_OrderProcessLog_descriptor,
        new String[] { "Quarter", "Id", "OrderId", "Action", "ActionComment", "StatusFlag", "Status", "StatusValue", "CloseFlag", "CreateBy", "CreateDate", "Remarks", });
    MQCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
